### ISSUE TITLE
unclear message regarding unsigned/bad signed applet - no jar mentioned

### ISSUE THREAD

**Issue by undergraver** [karakun/OpenWebStart#120]
The problem is the fact that I don't have any clues where to start debugging this from my application. Mentioning the jar file might be helpful.

Please let me know If I can provide other information.

**** I attached the start of the java log (with error) ****
```
Launch exception
netx: Initialization Error: Could not initialize applet. (Fatal: Application Error: The JNLP application is not fully signed by a single cert. The JNLP application has its components individually signed, however there must be a common signer to all entries.)
netx: Initialization Error: Could not initialize applet. (Fatal: Application Error: The JNLP application is not fully signed by a single cert. The JNLP application has its components individually signed, however there must be a common signer to all entries.)
```

**** Show Details error log ****
```
net.sourceforge.jnlp.LaunchException: Fatal: Initialization Error: Could not initialize applet. For more information click "more information button".
	at net.sourceforge.jnlp.Launcher.createApplet(Launcher.java:573)
	at net.sourceforge.jnlp.Launcher.launchApplet(Launcher.java:489)
	at net.sourceforge.jnlp.Launcher.access$300(Launcher.java:69)
	at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:664)
Caused by: net.sourceforge.jnlp.LaunchException: Fatal: Application Error: The JNLP application is not fully signed by a single cert. The JNLP application has its components individually signed, however there must be a common signer to all entries.
	at net.sourceforge.jnlp.runtime.JNLPClassLoader$SecurityDelegateImpl.getClassLoaderSecurity(JNLPClassLoader.java:2218)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.setSecurity(JNLPClassLoader.java:385)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.initializeResources(JNLPClassLoader.java:773)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.<init>(JNLPClassLoader.java:348)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.createInstance(JNLPClassLoader.java:421)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.getInstance(JNLPClassLoader.java:493)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.getInstance(JNLPClassLoader.java:466)
	at net.sourceforge.jnlp.Launcher.createApplet(Launcher.java:534)
	... 3 more
```

**Comment by sclassen** [comment]
The message says that there all your jars are signed.
But there is no single certificate which signed all of the jars.
You need to make sure that there is a certificate which signed each and every one of the jars required for your application

**Comment by undergraver** [comment]
Agree with that. 

A good approach would be to show a more detailed information about the certificates used for each jar file as there are many jar files in our legacy application.

If you can point me to the code responsible for this I might be able to contribute in my spare time.

**Comment by sclassen** [comment]
The code for checking the signatures revolves around the JNLPClassloader in the icedtea-web project. But this part of the code is in a rather "crude" state.
We will tackle lazy loading of resources next and in the process we might fimd time to start separating the different responsabilities currently swirrled together in the JNLPClassloader

**Comment by undergraver** [comment]
Hi @sclassen 
Any news on this? I can help with testing, at least. We have some jar files that are signed with the same certificate but still we get that error and we don't know where the issue resides. That means having a more detailed log would definitely help.
Thanks!

**Comment by sclassen** [comment]
It is more work as expected.
But we will get there, eventually  :imp:

**Comment by sclassen** [comment]
will be part of 1.2.0

**Comment by undergraver** [comment]
Great news! Can't wait to test that.

**Comment by AndreasEhret** [comment]
please test with 3.0.0-alpha1

**Comment by Jamila891** [comment]
closed due to inactivity
