### ISSUE TITLE
UnsupportedOperationException for AbstractList in OwsJvmLauncher.getJavaRuntime()

### ISSUE THREAD

**Issue by FelixJongleur42** [karakun/OpenWebStart#123]
```
net.sourceforge.jnlp.LaunchException: Fatal: External Launch Error: Could not launch JNLP file. The application has not been initialized, for more information execute javaws/browser from the command line and send a bug report.
	at net.sourceforge.jnlp.Launcher.launchExternal(Launcher.java:288)
	at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:364)
	at net.sourceforge.jnlp.Launcher.access$200(Launcher.java:69)
	at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:661)
Caused by: java.lang.UnsupportedOperationException
	at java.util.AbstractList.add(AbstractList.java:148)
	at java.util.AbstractList.add(AbstractList.java:108)
	at com.openwebstart.launcher.OwsJvmLauncher.getJavaRuntime(OwsJvmLauncher.java:62)
	at com.openwebstart.launcher.OwsJvmLauncher.launchExternal(OwsJvmLauncher.java:53)
	at net.sourceforge.jnlp.Launcher.launchExternal(Launcher.java:284)
	... 3 more
```

This is the corresponding Code Snippet
```
        final List<JREDesc> jres = Arrays.asList(jnlpFile.getResources().getJREs());
        if (jres.isEmpty()) {
            jres.add(getDefaultJRE());
        }
```
you can't do an add() to a list that resulted from Arrays.asList()

**Comment by FelixJongleur42** [comment]
Wow, that was quick ;)
