### ISSUE TITLE
Error parsing JNLP-File

### ISSUE THREAD

**Issue by Kroki0815** [karakun/OpenWebStart#149]
Hi,
i get the following error when trying to start the attached jnlp-file:

```
net.sourceforge.jnlp.LaunchException: Fatal: Read Error: Could not read or parse the JNLP file. You can try to download this file manually and send it as bug report to IcedTea-Web team.
	at net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:329)
	at net.sourceforge.jnlp.Launcher.launch(Launcher.java:190)
	at net.sourceforge.jnlp.runtime.Boot.launch(Boot.java:345)
	at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:325)
	at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:73)
	at java.security.AccessController.doPrivileged(Native Method)
	at net.sourceforge.jnlp.runtime.Boot.runMain(Boot.java:269)
	at net.sourceforge.jnlp.runtime.Boot.mainWithReturnCode(Boot.java:127)
	at net.sourceforge.jnlp.runtime.Boot.main(Boot.java:111)
	at com.openwebstart.launcher.PhaseTwoWebStartLauncher.main(PhaseTwoWebStartLauncher.java:80)
	at com.openwebstart.launcher.OpenWebStartLauncher.main(OpenWebStartLauncher.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:85)
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)
	at com.install4j.runtime.launcher.WinLauncher.main(WinLauncher.java:25)
Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: '1.6+ 1.5+ ' is not a valid version-string according to JSR-56, Appendix A.
	at net.sourceforge.jnlp.JNLPFile.parse(JNLPFile.java:887)
	at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:291)
	at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:273)
	at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:258)
	at net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:297)
	... 17 more
```

[test.jnlp.txt](https://github.com/karakun/OpenWebStart/files/4012562/test.jnlp.txt)

Openwebstart-Version: 1.1.1
OS: Windows 10 64Bit

**Comment by sclassen** [comment]
You are not allowed to mention multiple java versions in a single j2se/java element.
If you want to support multiple java versions you can either specify multiple j2se/java elements or use wildcards to mach multiple versions.
E.g.: 
- `1.5+` matches any java version greater or equal to 1.5
- `1.5*` matches any java version starting with 1.5
