### ISSUE TITLE
Webstart App gets Linkage Error with OWS 1.1.1

### ISSUE THREAD

**Issue by AM-Xdev** [karakun/OpenWebStart#153]
After fixing https://github.com/karakun/OpenWebStart/issues/124 we are now getting this error:

With Tattletale i check if we have this class in to different Jars but it only exists in one.
```
14:46:19 ERROR [util.task.XdevTaskQueue      ]  [XTQ_PEMVI pool-5-thread-1] java.lang.LinkageError
     at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
     at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
     at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
     at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
     at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:603)
     at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:678)
     at java.base/java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:722)
     at gui.shared.ei.NavigationsTree.init(NavigationsTree.java:293)
     at gui.shared.ei.PageTree.getNavigationsTree(PageTree.java:44)
     at gui.shared.ei.WndMainWindow$2.run(WndMainWindow.java:169)
     at util.task.XdevTaskQueue$1.run(XdevTaskQueue.java:105)
     at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
     at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
     at java.base/java.lang.Thread.run(Thread.java:834)
 Caused by: java.lang.LinkageError: loader net.sourceforge.jnlp.runtime.JNLPClassLoader @2f21453c attempted duplicate class definition for com.jidesoft.plaf.basic.BasicJideButtonUI. (com.jidesoft.plaf.basic.BasicJideButtonUI is in unnamed module of loader net.sourceforge.jnlp.runtime.JNLPClassLoader @2f21453c, parent loader 'bootstrap')
     at java.base/java.lang.ClassLoader.defineClass1(Native Method)
     at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
     at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
     at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:550)
     at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
     at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
     at java.base/java.security.AccessController.doPrivileged(Native Method)
     at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
     at net.sourceforge.jnlp.runtime.JNLPClassLoader.access$1301(JNLPClassLoader.java:114)
     at net.sourceforge.jnlp.runtime.JNLPClassLoader.lambda$findClass$12(JNLPClassLoader.java:1580)
     at java.base/java.security.AccessController.doPrivileged(Native Method)
     at net.sourceforge.jnlp.runtime.JNLPClassLoader.findClass(JNLPClassLoader.java:1579)
     at net.sourceforge.jnlp.runtime.JNLPClassLoader.loadClassExt(JNLPClassLoader.java:1611)
     at net.sourceforge.jnlp.runtime.JNLPClassLoader.lambda$loadClass$6(JNLPClassLoader.java:1427)
     at net.sourceforge.jnlp.runtime.JNLPClassLoader$ExceptionalSupplier.getResultOfCallOrNull(JNLPClassLoader.java:1391)
     at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
     at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1631)
     at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
     at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
     at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
     at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
     at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
     at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
     at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
     at net.sourceforge.jnlp.runtime.JNLPClassLoader.loadClass(JNLPClassLoader.java:1434)
     at java.desktop/javax.swing.UIDefaults.getUIClass(UIDefaults.java:719)
     at java.desktop/javax.swing.UIDefaults.getUI(UIDefaults.java:786)
     at java.desktop/javax.swing.UIManager.getUI(UIManager.java:1066)
     at com.jidesoft.swing.JideButton.updateUI(Unknown Source)
     at java.desktop/javax.swing.AbstractButton.init(AbstractButton.java:2136)
     at java.desktop/javax.swing.JButton.<init>(JButton.java:131)
     at java.desktop/javax.swing.JButton.<init>(JButton.java:85)
     at com.jidesoft.swing.JideButton.<init>(Unknown Source)
     at com.jidesoft.swing.JideButton.<init>(Unknown Source)
     at component.IShortDescriptableValueChooserTextField$IJideButton.<init>(IShortDescriptableValueChooserTextField.java:806)
     at component.IShortDescriptableValueChooserTextField.createButton(IShortDescriptableValueChooserTextField.java:265)
     at xdev.ui.valuechooser.ValueChooserTextField.a(SourceFile:170)
     at xdev.ui.valuechooser.ValueChooserTextField.<init>(SourceFile:122)
     at component.IShortDescriptableValueChooserTextField.<init>(IShortDescriptableValueChooserTextField.java:124)
     at gui.shared.ei.editabletable.PageBonusgruppeEditor.<init>(PageBonusgruppeEditor.java:465)
     at gui.shared.ei.NavigationsTree.lambda$30(NavigationsTree.java:933)
     at gui.shared.ei.NavigationsTree$NavigationAction.compute(NavigationsTree.java:1763)
     at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
     at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
     at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
     at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
     at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
     at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

[itw-clienta-2020-01-08_14_41_39.318.log](https://github.com/karakun/OpenWebStart/files/4035588/itw-clienta-2020-01-08_14_41_39.318.log)
[itw-javantx-2020-01-08_14_42_21.297.log](https://github.com/karakun/OpenWebStart/files/4035585/itw-javantx-2020-01-08_14_42_21.297.log)

**Comment by hendrikebbers** [comment]
can you please check if the exact same error happens all the time? This looks to me like a race condition.

**Comment by AM-Xdev** [comment]
Your are right after redeploying the App after one week, the error is gone.
