### ISSUE TITLE
OpenWebStart update does not work

### ISSUE THREAD

**Issue by ywuliu** [karakun/OpenWebStart#174]
The new OpenWebStart version 1.1.3  is online, I did not see any hint for updating when I start my app. 
In the same time, when I try to "Check or update now" in setting, return error
![Screen Shot 2020-01-27 at 4 51 49 PM](https://user-images.githubusercontent.com/39272732/73217458-f64c1c80-4125-11ea-9fed-dda792eefb7e.png)

**Comment by sclassen** [comment]
Can you provide us a log file with the error in it

**Comment by ywuliu** [comment]
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1946)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:316)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:310)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1639)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:223)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1037)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:965)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1064)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:162)
	at com.install4j.runtime.installer.helper.content.HttpRequestHandler.getURLConnection(HttpRequestHandler.java:288)
	at com.install4j.runtime.installer.helper.content.HttpRequestHandler.connect(HttpRequestHandler.java:135)
	at com.install4j.runtime.installer.helper.content.Downloader.connect(Downloader.java:155)
	at com.install4j.runtime.installer.helper.content.Downloader.connect(Downloader.java:24)
	at com.install4j.runtime.installer.helper.content.HttpRequestHandler.connect(HttpRequestHandler.java:128)
	at com.install4j.runtime.installer.helper.content.Downloader.connect(Downloader.java:150)
	at com.install4j.runtime.installer.helper.apiimpl.UpdateCheckerImpl.getUpdateDescriptor(UpdateCheckerImpl.java:31)
	at com.install4j.api.update.UpdateChecker.getUpdateDescriptor(UpdateChecker.java:65)
	at com.openwebstart.install4j.Install4JUpdateHandler.getUpdate(Install4JUpdateHandler.java:57)
	at com.openwebstart.install4j.Install4JUpdateHandler.hasUpdate(Install4JUpdateHandler.java:43)
	at com.openwebstart.update.UpdatePanel.lambda$null$4(UpdatePanel.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:397)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:302)
	at sun.security.validator.Validator.validate(Validator.java:262)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1621)
	... 24 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:392)
	... 30 more

**Comment by sclassen** [comment]
Please a full Log.
The stacktrace does not even include to which server/url it is trying to connect

**Comment by ywuliu** [comment]
[itw-javantx-2020-01-28_08:01:52.593.log](https://github.com/karakun/OpenWebStart/files/4122855/itw-javantx-2020-01-28_08.01.52.593.log)

**Comment by ywuliu** [comment]
I am aware that, when I use curl https://download-openwebstart.com/updates/updates.xml in command line in Mac, everything works. suggestion: can add Option for exception in program for this case: when get the this exception, using command line to get the data?

**Comment by sclassen** [comment]
more than strange. The trust store of the bundled JVM contains the correct CA.
Can you uninstall your current OWS and download and install the version 1.1.3 from here:
https://github.com/karakun/OpenWebStart/releases/tag/v1.1.3

This should give you a clean setup.
If the error still occurs it might be related your deployment.properties or a funny proxy/network issue...

**Comment by AndreasEhret** [comment]
close due to inactivity
