### ISSUE TITLE
Use SapMC

### ISSUE THREAD

**Issue by Simon0Harms** [karakun/OpenWebStart#213]
I suppose this is a applet-error and not supported?
```
net.sourceforge.jnlp.LaunchException: Fatal: Launch Error: Could not launch JNLP file. The application has not been initialized, for more information execute javaws/browser from the command line and send a bug report.
	at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:406)
	at net.sourceforge.jnlp.Launcher.access$200(Launcher.java:69)
	at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:650)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:400)
	... 2 more
Caused by: java.lang.NoClassDefFoundError: sun/applet/AppletClassLoader
	at com.sap.plaf.frog.FrogLookAndFeel.<clinit>(FrogLookAndFeel.java:101)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:427)
	at java.desktop/javax.swing.SwingUtilities.loadSystemClass(SwingUtilities.java:2036)
	at java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:632)
	at com.sap.managementconsole.swing.main.ManagementConsole.startWindow(ManagementConsole.java:287)
	at com.sap.managementconsole.swing.main.ManagementConsole.main(ManagementConsole.java:341)
	... 7 more
Caused by: java.lang.ClassNotFoundException: sun.applet.AppletClassLoader
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.lambda$loadClass$9(JNLPClassLoader.java:1432)
	at java.base/java.util.Optional.orElseThrow(Optional.java:401)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.loadClass(JNLPClassLoader.java:1432)
	... 14 more
```

**Comment by sclassen** [comment]
Can you share your application so we can reproduce.

**Comment by sclassen** [comment]
Also the complete log would be very helpful
