### ISSUE TITLE
Open JFX application is not opening in Open Web Start Plugin

### ISSUE THREAD

**Issue by yuvraj18yadav** [karakun/OpenWebStart#264]
My application is launching perfectly with openwebstart plugin.  I am using Azul open jdk+open jfx bundle configured using jvm manager . Most of jfx apploications are running smoothly one application is giving me trouble . Application is not launching and in the logs we are getting exception . Please find below the exception logs 

```
>>> ERROR occurred on Thu May 14 14:46:55 IST 2020
javafx.fxml.LoadException: BorderPane is not a valid type.
file:/Users/ysingh/Desktop/SM-Installer-Enhancements/webstart/12.72/ome12720aa76_webstart/OME/release/gen12720aa01_genRelease.jar!/com/ciena/optical/viking/otdr/fx/client/OtdrView.fxml

	at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2597)
	at javafx.fxml.FXMLLoader.createElement(FXMLLoader.java:2774)
	at javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2704)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2527)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2409)
	at com.ciena.optical.viking.otdr.fx.client.OtdrFxViewAdapter$1.run(OtdrFxViewAdapter.java:150)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
```

**Comment by janakmulani** [comment]
Please see if this helps : https://github.com/karakun/OpenWebStart/blob/master/documentation/faq/FAQ.adoc#how-to-run-openjfx-based-javafx-applications-with-openwebstart
