### ISSUE TITLE
Could Not Launch JNLP file on MacOS

### ISSUE THREAD

**Issue by rdemaeye** [karakun/OpenWebStart#27]
- OpenWebStart 0.3.1

- Mac OS 10.13.4

- JNLP file launches without issue with Oracle WebStart as well as with IcedTea-Web on Windows

Error shown after launch failure

`net.sourceforge.jnlp.LaunchException: Fatal: Launch Error: Could not launch JNLP file. The application has not been initialized, for more information execute javaws/browser from the command line and send a bug report.
	at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:459)
	at net.sourceforge.jnlp.Launcher.access$400(Launcher.java:70)
	at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:782)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:453)
	... 2 more
Caused by: java.lang.NoSuchMethodError: 'void com.apple.eawt.Application.removeAboutMenuItem()'
	at com.prosc.mirror.config.ConfigClient.main(ConfigClient.java:69)
	... 7 more
`
executing javaws/browser does not work as there is no JavaWS on this machine

Java Console logs
[openwebstart.log](https://github.com/karakun/OpenWebStart/files/3584127/openwebstart.log)

**Comment by sclassen** [comment]
can you remove all your JVMs in the OpenWebStart Settings and try again

**Comment by sclassen** [comment]
We found and fixed an issue when starting applications using Java 11.
Can you download and test if you application runs with the newest version 0.3.2
https://openwebstart.com/download/

**Comment by rdemaeye** [comment]
The only JVM showing in Settings is 11.0.4 AdoptOpenJDK which was installed by the openwebstart installer. I tried with 0.3.2 and received the same error. Logs attached 
[javalogsopenwebstart.txt](https://github.com/karakun/OpenWebStart/files/3601112/javalogsopenwebstart.txt)

**Comment by AndreasEhret** [comment]
according to logs you are try to launch your app with a 11.0.4 AdoptOpenJDK and rely on Mac OS X com.apple.eawt package which is no longer be accessible with 9+. I assume this causes your problem.

see 
- https://github.com/triplea-game/triplea/issues/3297
- http://openjdk.java.net/jeps/272

Did you try with a JVM 1.8*? You can set this in the JVM Manager settings: https://openwebstart.com/jvm-manager

**Comment by sclassen** [comment]
closing this issue as there was no further feedback.
Please feel free to reopen if you can still reproduce.
