### ISSUE TITLE
Dell C6220II KVM-IP

### ISSUE THREAD

**Issue by JPlanche** [karakun/OpenWebStart#28]
I tried OpenWebStart V0.3.1 with the KVM-IP of a Dell C6220II server.
The applet runs but I have immediately the message "'Connection is closed".

It works with Sun Java 6 (yes, _newer_ versions sometimes don't work with old hardware so I use specifically an old version).

The logs:
[itw-javantx.log](https://github.com/karakun/OpenWebStart/files/3585274/itw-javantx.log)
[itw-clienta.log](https://github.com/karakun/OpenWebStart/files/3585273/itw-clienta.log)

Hope it helps (but also hope it helps me ;-))

**Comment by sclassen** [comment]
From the logs:
```
Fri Sep 06 20:20:27 CEST 2019 [ERROR  ] net.sourceforge.jnlp.cache.ResourceDownloader:
ERROR
net.sourceforge.jnlp.cache.ResourceDownloader$RedirectionException: The resource http://192.168.9.184:80/images/logo.gif is 
being redirected (302) to https://192.168.9.184/login.html. This is disabled by default. If you wont to allow it, run javaws 
with -allowredirect parameter.
```

Can you fix your server to not require a login to download the resources?
Also limit you JVM in the settings to 1.8* instead of 1.8+

**Comment by JPlanche** [comment]
> Can you fix your server to not require a login to download the resources?
It's the BMC of a server, I have no control over it.

(I tried but didn't succeed to run the JNLP with the -allowredirect parameter.)

> Also limit you JVM in the settings to 1.8* instead of 1.8+
I have now 1.8.0_222 AdoptOpenJDk in the JVM Manager tab (with 11.0.4)  but there's no difference. Should I do something?

Sorry, I don't much about Java, it's magic for me.
I could be more precise

**Comment by sclassen** [comment]
Regarding the Java 11 issue we have release a fix. Please try 0.3.2
https://openwebstart.com/download/

For the commandline option `-allowredirect`: if you can tell me which OS you are using I can give you a hint on how to pass the command line flag

**Comment by JPlanche** [comment]
> Regarding the Java 11 issue we have release a fix. Please try 0.3.2
> https://openwebstart.com/download/

I tried 0.3.2 but there's no difference.

> For the commandline option `-allowredirect`: if you can tell me which OS you are using I can give you a hint on how to pass the command line flag

I'm currently using Windows Server 2012 for this tests.

Seeing in the logs:
`Connection failed with exception: No appropriate protocol (protocol is disabled or cipher suites are 
inappropriate)`
I thought of commenting in C:\Program Files\OpenWebStart\jre\lib\security\java.security
the lines *disabledAlgorithms with no success.

**Comment by sclassen** [comment]
Ok, so Windows it is  :)

1. Open a PowerShell window
2. Navigate to the OpenWebstart install directory (most likely: `C:\Program Files\OpenWebStart`
3. Run the following command
`.\javaws.exe -allowredirect -jnlp "<path or url to JNLP file>" -console`
4. in case of error please post the logs

You need to replace `<path or url to JNLP file>` with the actual path or URL. But please keep the quotes around the path as openwebstart will get hickups if you pass spaces in a unquoted path...

the `-console` option enables console output so you can see directly what is going on. The log files are written in addition (if you have turned them on in the settings under debugging) so you can leave the -console away if you don't want to see it in the power shell.

**Comment by JPlanche** [comment]
OK, I was using cmd.exe and the folder where there's the JNLP file as $PWD.

I tried exactly what you said and here's the log:
[itw-javantx-2019-09-10.log](https://github.com/karakun/OpenWebStart/files/3597535/itw-javantx-2019-09-10.log)

Thank you for your attention.
Maybe this BMC rubbish is too old?

**Comment by sclassen** [comment]
Sorry for the long silence. Does your problem still persist?
Your last log you posted does not contain any error messages.

**Comment by JPlanche** [comment]
You're welcome.
Yes, it does persist.

Could I send you privately the credentials so you could have a look?

**Comment by sclassen** [comment]
Yes, you can send anything to openwebstart@karakun.com
All mails are treated as confidential unless you give us other permissions

**Comment by JPlanche** [comment]
As we saw privately, this applet is working with Amazon Corretto 1.8.0_232 (the ciphers used by this old thing are... old).

Thank you for your time!

**Comment by kscheel** [comment]
Hey there, I'm also trying to connect to an old iDRAC 6 console, I'm so glad OpenWebStart exists 🥳  

After some fiddling I got it running. I guess this will be trivial for most people, but maybe some will find it helpful, these are the steps it took me:

- Download and extract an archive of the old Coretto 8.232.09.1 JVM from https://github.com/corretto/corretto-8/releases/tag/8.232.09.1
- Launch "OpenWebStart Settings"
- go to JVM Manager
- Use the Add button and select the folder where you extracted the JVM earlier
- make sure no other JVMs are enabled
- Optional: Click the Settings Button and disable JVM Updates (or simply don't download newer JVMs when OpenWebStart asks you to)
- Log in to iDRAC and launch the virtual console
- a download will start, save the file and rename it to "viewer.jnlp"
- launch viewer.jnlp

cheers! 🙂

**Comment by gerhard** [comment]
I am trying to connect to iDRAC 7 but failing to do so. I am using:

* OpenWebStart `1.7.0`
* `17.0.5 Eclipse Adoptium`

This is what I get when I run `viewer.jnlp`:

<img width="464" alt="image" src="https://user-images.githubusercontent.com/3342/206595533-447ea431-3e7d-4e89-aca7-dd8af4a73808.png">

This is the error that I'm seeing in `~/.config/icedtea-web/log/2022-12-09_00:31:20.423-ows-stage2.log`:

```log
[ITW-CORE][2022-12-09 00:31:26.179 GMT][DEBUG][net.sourceforge.jnlp.runtime.CachedJarFileCallback] Class-Path attribute cleared for /Users/gerhard/.cache/icedtea-web/cache/0/2/avctKVM.jar
[ITW-APP ][2022-12-09 00:31:26.198 GMT][INFO ][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] MAC OS X
[ITW-APP ][2022-12-09 00:31:26.224 GMT][INFO ][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] KVM/VM Client Version: 5.04.04 (Build 425)
[ITW-APP ][2022-12-09 00:31:26.250 GMT][INFO ][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] replace numpad
[ITW-APP ][2022-12-09 00:31:26.355 GMT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] java.lang.reflect.InvocationTargetException
[ITW-APP ][2022-12-09 00:31:26.355 GMT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] 	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1369)
[ITW-APP ][2022-12-09 00:31:26.355 GMT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] 	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1344)
[ITW-APP ][2022-12-09 00:31:26.355 GMT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] 	at java.desktop/javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1480)
[ITW-APP ][2022-12-09 00:31:26.355 GMT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] 	at com.avocent.app.c.l.p(Unknown Source)
[ITW-APP ][2022-12-09 00:31:26.355 GMT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] 	at com.avocent.app.c.l.e(Unknown Source)
[ITW-APP ][2022-12-09 00:31:26.355 GMT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] 	at com.avocent.idrac.kvm.a.e(Unknown Source)
[ITW-APP ][2022-12-09 00:31:26.355 GMT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] 	at com.avocent.idrac.kvm.Main.a(Unknown Source)
[ITW-APP ][2022-12-09 00:31:26.355 GMT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] 	at com.avocent.idrac.kvm.Main.main(Unknown Source)
[ITW-APP ][2022-12-09 00:31:26.355 GMT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ITW-APP ][2022-12-09 00:31:26.356 GMT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[ITW-APP ][2022-12-09 00:31:26.356 GMT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ITW-APP ][2022-12-09 00:31:26.356 GMT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[ITW-APP ][2022-12-09 00:31:26.356 GMT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] 	at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:406)
[ITW-APP ][2022-12-09 00:31:26.356 GMT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] 	at net.sourceforge.jnlp.Launcher.access$300(Launcher.java:71)
[ITW-APP ][2022-12-09 00:31:26.356 GMT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] 	at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:660)
[ITW-APP ][2022-12-09 00:31:26.356 GMT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] Caused by: java.lang.IllegalAccessError: class com.avocent.app.b.bb (in unnamed module @0xcbf9199) cannot access class sun.java2d.SunGraphicsEnvironment (in module java.desktop) because module java.desktop does not export sun.java2d to unnamed module @0xcbf9199
[ITW-APP ][2022-12-09 00:31:26.356 GMT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] 	at com.avocent.app.b.bb.pack(Unknown Source)
[ITW-APP ][2022-12-09 00:31:26.356 GMT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] 	at com.avocent.app.c.v.run(Unknown Source)
[ITW-APP ][2022-12-09 00:31:26.356 GMT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] 	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:308)
[ITW-APP ][2022-12-09 00:31:26.356 GMT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
[ITW-APP ][2022-12-09 00:31:26.356 GMT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
[ITW-APP ][2022-12-09 00:31:26.356 GMT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
[ITW-APP ][2022-12-09 00:31:26.357 GMT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
[ITW-APP ][2022-12-09 00:31:26.357 GMT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
[ITW-APP ][2022-12-09 00:31:26.357 GMT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
[ITW-APP ][2022-12-09 00:31:26.357 GMT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
[ITW-APP ][2022-12-09 00:31:26.357 GMT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
[ITW-APP ][2022-12-09 00:31:26.357 GMT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
[ITW-APP ][2022-12-09 00:31:26.357 GMT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] 	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:191)
[ITW-APP ][2022-12-09 00:31:26.357 GMT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] 	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:236)
[ITW-APP ][2022-12-09 00:31:26.357 GMT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] 	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:234)
[ITW-APP ][2022-12-09 00:31:26.357 GMT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
[ITW-APP ][2022-12-09 00:31:26.357 GMT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] 	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:234)
[ITW-APP ][2022-12-09 00:31:26.357 GMT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] 	at java.desktop/java.awt.Dialog.show(Dialog.java:1080)
[ITW-APP ][2022-12-09 00:31:26.357 GMT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] 	at java.desktop/java.awt.Component.show(Component.java:1728)
[ITW-APP ][2022-12-09 00:31:26.357 GMT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] 	at java.desktop/java.awt.Component.setVisible(Component.java:1675)
[ITW-APP ][2022-12-09 00:31:26.357 GMT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] 	at java.desktop/java.awt.Window.setVisible(Window.java:1036)
[ITW-APP ][2022-12-09 00:31:26.357 GMT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] 	at java.desktop/java.awt.Dialog.setVisible(Dialog.java:1016)
[ITW-APP ][2022-12-09 00:31:26.357 GMT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] 	at com.openwebstart.download.ApplicationDownloadDialog.setVisible(ApplicationDownloadDialog.java:282)
[ITW-APP ][2022-12-09 00:31:26.357 GMT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] 	at com.openwebstart.ui.ModalDialog.showAndWait(ModalDialog.java:42)
[ITW-APP ][2022-12-09 00:31:26.357 GMT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] 	at com.openwebstart.download.ApplicationDownloadDialog.showAndWait(ApplicationDownloadDialog.java:275)
[ITW-APP ][2022-12-09 00:31:26.358 GMT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] 	at com.openwebstart.download.ApplicationDownloadDialog.updateUi(ApplicationDownloadDialog.java:186)
[ITW-APP ][2022-12-09 00:31:26.358 GMT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] 	at com.openwebstart.download.ApplicationDownloadDialog.lambda$onUpdate$2(ApplicationDownloadDialog.java:177)
[ITW-APP ][2022-12-09 00:31:26.358 GMT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] 	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
[ITW-APP ][2022-12-09 00:31:26.358 GMT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
[ITW-APP ][2022-12-09 00:31:26.358 GMT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
[ITW-APP ][2022-12-09 00:31:26.358 GMT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
[ITW-APP ][2022-12-09 00:31:26.358 GMT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
[ITW-APP ][2022-12-09 00:31:26.358 GMT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
[ITW-APP ][2022-12-09 00:31:26.358 GMT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
[ITW-APP ][2022-12-09 00:31:26.358 GMT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
[ITW-APP ][2022-12-09 00:31:26.358 GMT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
[ITW-APP ][2022-12-09 00:31:26.358 GMT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
[ITW-APP ][2022-12-09 00:31:26.358 GMT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
[ITW-APP ][2022-12-09 00:31:26.358 GMT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
[ITW-APP ][2022-12-09 00:31:26.358 GMT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
[ITW-CORE][2022-12-09 00:31:27.469 GMT][DEBUG][com.openwebstart.download.ApplicationDownloadIndicator] Closing DownloadServiceListener
[ITW-CORE][2022-12-09 00:33:26.864 GMT][INFO ][net.sourceforge.jnlp.util.logging.OutputController] Increase polling interval for shutdown phase
[ITW-CORE][2022-12-09 00:33:26.864 GMT][DEBUG][net.sourceforge.jnlp.runtime.JNLPRuntime] Releasing shared lock on /var/folders/z5/n5y08g4j073_ld2d9019j3_80000gn/T/gerhard/netx/locks/netx_running
[ITW-CORE][2022-12-09 00:33:26.864 GMT][DEBUG][net.sourceforge.jnlp.runtime.JNLPRuntime] Closing channel
[ITW-CORE][2022-12-09 00:33:26.864 GMT][DEBUG][net.sourceforge.jnlp.runtime.JNLPRuntime] Releasing done
[ITW-CORE][2022-12-09 00:33:26.864 GMT][INFO ][net.sourceforge.jnlp.cache.NativeLibraryStorage] Cleaning up native directory /var/folders/z5/n5y08g4j073_ld2d9019j3_80000gn/T/netx-native-39131
[ITW-CORE][2022-12-09 00:33:26.864 GMT][DEBUG][net.adoptopenjdk.icedteaweb.io.FileUtils] Deleting: /var/folders/z5/n5y08g4j073_ld2d9019j3_80000gn/T/netx-native-39131
[ITW-CORE][2022-12-09 00:33:26.864 GMT][DEBUG][net.adoptopenjdk.icedteaweb.resources.cache.CacheImpl] preparing to cleanup the cache
[ITW-CORE][2022-12-09 00:33:26.865 GMT][INFO ][net.adoptopenjdk.icedteaweb.resources.cache.CacheImpl] Other instances of javaws are running
[ITW-CORE][2022-12-09 00:33:26.865 GMT][INFO ][net.adoptopenjdk.icedteaweb.resources.cache.CacheImpl] Cannot clear the cache at this time. Try later. If the problem persists, try closing your browser(s) & JNLP applications. At the end you can try to kill all java applications. You can clear cache by javaws -Xclearcache or via itw-settings Cache -> View files -> Purge
[ITW-CORE][2022-12-09 00:33:26.865 GMT][DEBUG][net.adoptopenjdk.icedteaweb.io.FileUtils] Deleting: /var/folders/z5/n5y08g4j073_ld2d9019j3_80000gn/T/netx-native-39131/libVMAPI_DLL.jnilib
[ITW-CORE][2022-12-09 00:33:26.865 GMT][DEBUG][net.adoptopenjdk.icedteaweb.io.FileUtils] Deleting: /var/folders/z5/n5y08g4j073_ld2d9019j3_80000gn/T/netx-native-39131/libavctKVMIO.jnilib
```

Any idea why `[ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] Caused by: java.lang.IllegalAccessError: class com.avocent.app.b.bb (in unnamed module @0xcbf9199) cannot access class sun.java2d.SunGraphicsEnvironment (in module java.desktop) because module java.desktop does not export sun.java2d to unnamed module @0xcbf9199` is happening?

Thanks!

**Comment by JPlanche** [comment]
Hello @gerhard 
This issue is closed and is about Dell C6220II (which have not DRAC).
You should create a new issue.

(You can use HTML5 with DRAC >6. Why bother with Java when you can use HTML5?)

**Comment by gerhard** [comment]
That's not a problem, I'm OK to leave it at this. I solved my issue via **Safe boot**.

I know that this is unrelated, but HTML 5 doesn't seem to be working in my iDRAC 7:
<img width="662" alt="Screenshot 2022-12-13 at 17 53 42" src="https://user-images.githubusercontent.com/3342/207637080-bd35a8a2-9b67-4026-9e71-e99ac30b5955.png">

Happy to leave it at this. Thanks for your help!
