### ISSUE TITLE
doesn't start in OS X

### ISSUE THREAD

**Issue by rdp** [karakun/OpenWebStart#280]
After installing it, when I double click a jnlp file, it says `To open this Web Start application you need to download the Java Runtime Environment click "More info..." to visit the website for the Java Runtime Environment.`

Note: I have JRE 7 installed.

Note: I have JDK 8 installed via homebrew.

Note: clicking "more info" takes me to https://plugins.apple.com/java-en?intent=WebStart&os_version=10.15.4&jrs_version=15.0.1 which redirects me to "get flash player"

Cheers!

For followers, the icedtea version works OK (command line only): https://apple.stackexchange.com/a/344129/25085

**Comment by sclassen** [comment]
@hendrikebbers please have a look

**Comment by ixs** [comment]
Stumbled over this as well, here's a hint:
/usr/bin/javaws is a symlink to /System/Library/Frameworks/JavaVM.framework/Versions/Current/Commands/javaws.

This in turn is a wrapper that checks, if a JRE/JDK provides a javaws binary. If not, the error message above is displayed.
A quick look at openwebstart seemed to confirm that OWS does not ship a javaws binary, which explains this error message...

**Comment by Jamila891** [comment]
@rdp can you test this again with the new version 1.2.1? Otherwise we're going to close this issue.

**Comment by rdp** [comment]
It got much farther.  Tried to load (some dialog boxes I couldn't tell what I was accepting), then

```
java.lang.IllegalStateException: could not find any suitable runtime
	at com.openwebstart.launcher.OwsJvmLauncher.getLocalJavaRuntimeOrExit(OwsJvmLauncher.java:70)
	at com.openwebstart.launcher.OwsJvmLauncher.launchExternal(OwsJvmLauncher.java:121)
	at com.openwebstart.launcher.OwsJvmLauncher.launchExternal(OwsJvmLauncher.java:64)
	at net.sourceforge.jnlp.Launcher.launchExternal(Launcher.java:285)
	at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:366)
	at net.sourceforge.jnlp.Launcher.access$200(Launcher.java:70)
	at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:654)
```

Or maybe that's expected?  Cheers!

**Comment by sclassen** [comment]
Can you provide us with a full log?
There are different reasons why the above error occurs. Without the log we cannot help here.

**Comment by rdp** [comment]
Hmm log dir is empty.
After opening it "separately" and adding some JVM's it works now.  Maybe it should prompt you to setup if there are no JVM's?  Cheers!

**Comment by sclassen** [comment]
Actually if there are no JVMs it should download one automatically.
That is why I was asking for the log to see why it could not download.
Logs need to be enabled in the settings.
So if you want to help us hunt down the root cause you can do the following:

1. Enable log to file in the settings
2. Remove the JVM from the list of known JVMs in the settings
3. Start the application and send us the logs created from the failed attempt.

**Comment by rdp** [comment]
Hmm not sure why it would want download a whole new one when the "auto detect" shows I have several "around".  Logs attached.
[2020-10-06_15:27:10.750-ows-stage1.log](https://github.com/karakun/OpenWebStart/files/5336898/2020-10-06_15.27.10.750-ows-stage1.log)
[2020-10-06_15:27:11.118-ows-stage1.log](https://github.com/karakun/OpenWebStart/files/5336899/2020-10-06_15.27.11.118-ows-stage1.log)
[2020-10-06_15:27:36.591-ows-settings.log](https://github.com/karakun/OpenWebStart/files/5336900/2020-10-06_15.27.36.591-ows-settings.log)

**Comment by sclassen** [comment]
Thank you for the logs. We will take it from here.

**Comment by rdp** [comment]
Unrelated, but here is a screenshot of one of the initial HTTPS prompts that was slightly confusing, am I downloading San Francisco? :)
<img width="611" alt="Screen Shot 2020-10-05 at 12 48 47 PM" src="https://user-images.githubusercontent.com/12496/95751074-4db1fe80-0c5b-11eb-964d-e4f7ef898e24.png">

**Comment by YAClydeM** [comment]
I'm on Ventura 13.5 and I was wondering if I could get /usr/bin/javaws to work with OpenWebStart.
```
$ which java
/usr/bin/java
$ which javaws
/usr/bin/javaws
$ /usr/bin/java -version
openjdk version "1.8.0_382"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_382-b05)
OpenJDK 64-Bit Server VM (Temurin)(build 25.382-b05, mixed mode)
$ /usr/bin/javaws -version
The operation couldn’t be completed. Unable to locate a Java Runtime that supports javaws.
Please visit http://www.java.com for information on installing Java.
$ ls /Applications/OpenWebStart/
App-Icon-512.png		OpenWebStart Settings.app	OpenWebStart javaws.app		readme.txt
Icon-512.png			OpenWebStart Uninstaller.app	openwebstart.jar
```

It would make things more convenient.
