### ISSUE TITLE
ClassNotFoundException: netscape.javascript.JSException

### ISSUE THREAD

**Issue by chris2606** [karakun/OpenWebStart#34]
The launch of Oracle Forms stops with the following error:

Caused by: java.lang.ClassNotFoundException: netscape.javascript.JSException 
    at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:787) 
    at net.sourceforge.jnlp.Launcher.access$500(Launcher.java:70) 
    at net.sourceforge.jnlp.Launcher.launchApplet(Launcher.java:534) 
    at net.sourceforge.jnlp.Launcher.createApplet(Launcher.java:644) 
    at java.lang.Class.newInstance(Class.java:412) 
    at java.lang.Class.getConstructor0(Class.java:3075) 
    at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671) 
    at java.lang.Class.getDeclaredConstructors0(Native Method) 
Caused by: java.lang.NoClassDefFoundError: netscape/javascript/JSException 
    at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:807) 
Exception in thread "PST Standard" java.lang.RuntimeException: java.lang.NoClassDefFoundError: netscape/javascript/JSException

Any ideas?

**Comment by sclassen** [comment]
Can you post the entire log and the JNLP file. This would help in narrowing down on the problem

**Comment by sclassen** [comment]
this is most likely related to the JVM used for launching oracle forms

**Comment by sclassen** [comment]
closing because of no response by the reporter
