### ISSUE TITLE
Cache Handling and Alternative setup for Linux

### ISSUE THREAD

**Issue by Yoshitha24** [karakun/OpenWebStart#380]
Hi,

We have recently migrated to OpenJDK 8. We require javaws to launch our .jnlp file. Initially we went for Adopt IcedTea for the same purpose but we are facing an issue over there and Adopt has recommended to use OpenWebStart for consistency. Please refer the ticket : https://github.com/AdoptOpenJDK/IcedTea-Web/issues/735

Below describes the problem I faced before with Adopt Icedtea: 
I have used a  scenario where we launch multiple GUIs using jnlp file on a Linux server. Initially I have launched one GUI and checked all the features and cache content. The features were working fine and I was able to locate all the jars mentioned in the jnlp files under different numbered folders. I repeated the above process for 9 GUIs and there was no problem. The cache folder structure is the same too. Note that I am not closing any GUIs but opening new ones.

However for the 10th GUI, I encountered the same problem where the the Auditing feature in my application doesn't work and I could see ClassNotFound exceptions. But the cache content is still the same and nothing has been modified. I have also checked the checksum of original jars present in server against the one present in .cache folder of icedtea-web. Both of them are the same.

I went ahead and launched the 11th GUI and the same problem persists. Again the cache content is not altered. On launching the 12th GUI, it was successful and all features are working fine. On launching the 13th GUI, the same Audit problem occurred once again. I have checked the cache content and nothing is altered. Also all the jars required and downloaded are present. I don't understand why some sessions are not able to access some jars.

I am currently testing my application with OpenWebStart. Can I get any comments on the issue I have faced and how it is handled in OpenWebStart.

Also we use RedHat Linux as our OS. So we are not able to install .deb files. Is it possible for you to provide an alternative like a zip file?

Thanks and Regards

**Comment by Jamila891** [comment]
@Yoshitha24 can you provide logging and maybe a sample application that contains the problem?

**Comment by Yoshitha24** [comment]
Hi,

Please see [feature_fail.txt](https://github.com/karakun/OpenWebStart/files/5853650/feature_fail.txt) . It contains the error which we get at times of inconsistency as explained before.

The error " com.bigbandnet.nms.service.ConnectorException: Can't get object with name Bigbandnet-NMS/Bigbandnet-NMS-Audit-AuditSession/remote " occurs whenever the functionality fails. The error is thrown by the JNDI lookup method (javax.naming.context --> lookup()) and caught as a NamingException. 
It looks something like below :
                               _Context ctx    = new InitialContext(env);
			       Object  object = ctx.lookup(objName); 
			       ctx.close();_

Providing a sample application would not be possible for us due to some restrictions and also the application requires a private connection to a server to run the application.

Also can you please update on providing an alternate for .deb file for Linux environment.

Thanks

**Comment by Yoshitha24** [comment]
Hi,

Can you please comment on providing an alternative package available for RedHat Linux environment (say a zip package or an rpm) as .deb package won't work for us. We would require that to test our application with OpenWebStart and check for  compatibility.

**Comment by sclassen** [comment]
we currently do not have the resources (both in persons and in machines) to implement and test more than one linux package.
But there is the possibility to sponsor features if this is a must have for your company.
If you are interested please contact us on openwebstart@karakun.com

**Comment by sclassen** [comment]
Looking into your log file I see `org.jboss.security.jndi.JndiLoginInitialContextFactory`
Is your application really launching a jboss server??

**Comment by Yoshitha24** [comment]
Hi,

We use jboss as an application server.

We are using OpenWebStart in our Linux server. We tried a scenario where we launch multiple GUIs say 2 GUIs in a Linux server using two different sessions (using putty) at the same time. While doing this during launch, "net.sourceforge.jnlp.LaunchException: Fatal: Launch Error: Could not launch JNLP file." error is seen and launching is terminated. 
![Fatal_Error_webstat_parallel_launch](https://user-images.githubusercontent.com/74032351/106584723-8bb99200-656c-11eb-9d24-141efd274e9c.PNG)


I could also see the following error in console:
_Cache is corrupt. Fixing.
Cache was corrupt and has been fixed. It is strongly recommended that you run 'javaws -Xclearcache' and rerun your application as soon as possible. You can also use via itw-settings Cache -> View files -> Purge_

**Is it not possible to launch two applications concurrently in the same environment?**

We also tried a different scenario. We logged into the same Linux server as two different users (OS level users like root, etc.) through two different sessions. We tried launching GUIs at the same time like before, but this time both the GUIs launched successfully. 

Can you please comment on the behavior?

Also in the second case where we used different OS level users, the changes/configurations we did in itw-settings for one user is not reflected when we login as different user. Do we have a setting where the change for one is reflected in all?

Also the Linux we use is RedHat Linux. So we used alien to convert .deb package to rpm package. Will this cause any problem?

**Comment by sclassen** [comment]
Ok I try to answer all the questions:

Yes it should be possible to launch multiple JNLPs (and also multiple instances of the same JNLP) with the same user.
Launching them with different users gives a higher separation as the cache is kept in the user's home folder.

There is a possibility to have a system wide configuration in addition to the per user configuration.
See https://openwebstart.com/docs/OWSGuide.html#_system_configuration

Converting the .deb into an rpm should not cause any troubles. The installer mainly copies the required files to /opt/OpenWebStart and registers the .jnlp file extension and some file icons. Nothing more

Now I have a question for you:
The stack trace in the screenshot looks like it has been taken from a very recent version of OpenWebStart.
But the output on the console you mention `Cache is corrupt. Fixing.` has been removed quite some time ago.
Do you have different versions of OpenWebStart installed or is there an icedtea-web version installed in addition to the OpenWebStart?
ITW and OWS use different file layout for the cache index thus one will inevitably corrupt the cache of the other...

**Comment by Yoshitha24** [comment]
Hi,
Thank you for answer our queries.

Regarding the _Cache is corrupt_ log on console, it is taken from iced-tea. I see that in that particular setup iced tea is also installed and hence the confusion. Sorry about that.

I do have have another query. We logged into the same Linux server as two different users (OS level users like root, etc.) through two different sessions (using MobaXterm) in the same PC. We tried launching two GUIs at the same time using OpenWebstart. Both the GUIs launched successfully but we can see an exception on the console.

_Exception in thread "AWT-EventQueue-1" java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
        at java.util.ArrayList.rangeCheck(ArrayList.java:659)
        at java.util.ArrayList.get(ArrayList.java:435)
        at java.awt.Container.createHierarchyEvents(Container.java:1444)
        at java.awt.Container.createHierarchyEvents(Container.java:1444)
        at java.awt.Container.createHierarchyEvents(Container.java:1444)
        at java.awt.Container.createHierarchyEvents(Container.java:1444)
        at java.awt.Container.createHierarchyEvents(Container.java:1444)
        at java.awt.Container.createHierarchyEvents(Container.java:1444)
        at java.awt.Container.createHierarchyEvents(Container.java:1444)
        at java.awt.Dialog.conditionalShow(Dialog.java:953)
        at java.awt.Dialog.show(Dialog.java:1045)
        at java.awt.Component.show(Component.java:1671)
        at java.awt.Component.setVisible(Component.java:1623)
        at java.awt.Window.setVisible(Window.java:1014)
        at java.awt.Dialog.setVisible(Dialog.java:1005)
        at com.openwebstart.download.ApplicationDownloadDialog.setVisible(ApplicationDownloadDialog.java:259)
        at com.openwebstart.ui.ModalDialog.showAndWait(ModalDialog.java:42)
        at com.openwebstart.download.ApplicationDownloadDialog.showAndWait(ApplicationDownloadDialog.java:252)
        at com.openwebstart.download.ApplicationDownloadDialog.updateUi(ApplicationDownloadDialog.java:163)
        at com.openwebstart.download.ApplicationDownloadDialog.lambda$onUpdate$2(ApplicationDownloadDialog.java:154)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
error when trying to load external property : https://10.39.234.154:8443/conf/brandInfo.properties_

Another exception observed :

_Exception in thread "AWT-EventQueue-0" java.util.ConcurrentModificationException
        at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1363)
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.findAny(ReferencePipeline.java:536)
        at com.openwebstart.download.ApplicationDownloadDetailListModel.remove(ApplicationDownloadDetailListModel.java:42)
        at com.openwebstart.download.ApplicationDownloadDialog.updateUi(ApplicationDownloadDialog.java:166)
        at com.openwebstart.download.ApplicationDownloadDialog.lambda$onUpdate$2(ApplicationDownloadDialog.java:154)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
        at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
        at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
        at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
        at java.awt.Dialog.show(Dialog.java:1084)
        at java.awt.Component.show(Component.java:1671)
        at java.awt.Component.setVisible(Component.java:1623)
        at java.awt.Window.setVisible(Window.java:1014)
        at java.awt.Dialog.setVisible(Dialog.java:1005)
        at com.openwebstart.download.ApplicationDownloadDialog.setVisible(ApplicationDownloadDialog.java:259)
        at com.openwebstart.ui.ModalDialog.showAndWait(ModalDialog.java:42)
        at com.openwebstart.download.ApplicationDownloadDialog.showAndWait(ApplicationDownloadDialog.java:252)
        at com.openwebstart.download.ApplicationDownloadDialog.updateUi(ApplicationDownloadDialog.java:163)
        at com.openwebstart.download.ApplicationDownloadDialog.lambda$onUpdate$2(ApplicationDownloadDialog.java:154)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
error when trying to load external property : https://10.39.234.154:8443/conf/brandInfo.properties_

Do you have any idea on the above mentioned exceptions.

**Comment by sclassen** [comment]
Sorry no

for every JNLP you launch a separate JVM instance is started. So except for file system and ports they should not interact with each other.
Do these exceptions also occur when only a single user is running a single application??
