### ISSUE TITLE
OpenWebStart issue loading classloader resource via URL in versions 1.3.0 and 1.3.1

### ISSUE THREAD

**Issue by martinhickson** [karakun/OpenWebStart#385]
An issue has been encountered when classloading resources in that it is trying to download the resource again from the server instead of loading the resources from the jar in the cache.  In addition, it is attempting to download via a .jar URL instead of .jar.pack.gz, which is the original URL used for the download.  This results in a FileNotFoundException as follows (URL generalized):

```
Caused by: java.io.FileNotFoundException: https://<host>:<port>/<URI>/<jar-name>.jar
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1915)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1507)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1505)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:795)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1504)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
	at net.adoptopenjdk.icedteaweb.http.CloseableConnection.getInputStream(CloseableConnection.java:58)
	at net.sourceforge.jnlp.runtime.CachedJarFileCallback.cacheJarFile(CachedJarFileCallback.java:140)
	at net.sourceforge.jnlp.runtime.CachedJarFileCallback.retrieve(CachedJarFileCallback.java:101)
	at java.base/sun.net.www.protocol.jar.URLJarFile.retrieve(URLJarFile.java:200)
	at java.base/sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:74)
	at java.base/sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:94)
	at java.base/sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:125)
	at java.base/sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:155)
	at java.base/java.net.URL.openStream(URL.java:1129)
	
...
```

The URL was obtained via a previous call to "getClass().getClassLoader().getResources("<xml-config-file>.xml")".

This code seems to be working fine in v1.2.1 and 3.0.0.alpha.  Is there likely to be another release in the 1.3.x series?

**Comment by sclassen** [comment]
Can you please attach the entire log and the JNLP file(s) to this issue.
If you do not want to make the content of theses files public you can send them to openwebstart@karakun.com

The next release is planned for mid April

**Comment by martinhickson** [comment]
Thanks for the feedback.  I did find a syntax issues in the JNLP file, but the cause of the problem turned out to be the META-INF/INDEX.LIST file, which resulted in the default JDK URLClassloader style behavior of trying to load the jar from the server.  The solution was to remove the INDEX.LIST file.

**Comment by in-fke** [comment]
As a heads up, `org.jboss.logging.jboss-logging_3.4.1.Final.jar` contains `INDEX.LIST` which then mentions `jboss-logging-3.4.1.Final.jar`. OWS tries to load the file from the server but fails (of course), but OWS continues.
Log does not complain about 404 when jar from INDEX.LIST is not found. The whole log about this "incident"
```
[ITW-CORE][2022-12-01 01:02:02.684 MEZ][INFO ][net.sourceforge.jnlp.runtime.CachedJarFileCallback] could not find mapping for <BASE-URL>/jboss-logging-3.4.1.Final.jar - falling back to downloading without caching
[ITW-CORE][2022-12-01 01:02:02.684 MEZ][DEBUG][com.openwebstart.proxy.direct.DirectProxyProvider] Using NO_PROXY for <BASE-URL>/jboss-logging-3.4.1.Final.jar
```

**Comment by fleminra** [comment]
Just to add to this (to make this specific issue searchable): XMLBeans versions prior to 3.1.0 contain an `INDEX.LIST` whose header states `xbean.jar`, apparently incorrectly. In newer versions of XMLBeans, that was changed to `xmlbeans.jar`. Anyway, this caused the application to try to download `xbean.jar` many times, with delays of 5–10 sec.
