### ISSUE TITLE
Corrupted Jar File from Cache makes JarCertVerifier stumble, Error for User should state that Jar is incomplete/corrupt

### ISSUE THREAD

**Issue by in-fke** [karakun/OpenWebStart#400]
Apparently a jar was not downloaded correctly yielding in an invalid Jar (the fact that this is possible should be a separate ticket).
The "non-user-friendly" error says that the signature could not be verified.
Instead it should state that the Jar is corrupt in the first place (e.g. looking at the root cause) and that deleting the cache would help.
This is another ticket to improve "user-friendliness" and "user acceptance" and to avoid 1st-Level support.

```
[ITW-CORE][2021-03-01 11:53:09.812 MEZ][DEBUG][net.sourceforge.jnlp.tools.JarCertVerifier] Jar found at C:\Users\fke\.cache\icedtea-web\cache\0\7\org.eclipse.equinox.security.win32.x86_64_1.1.200.v20190812-0919.jar has been verified as SIGNED_OK
[ITW-CORE][2021-03-01 11:53:09.815 MEZ][ERROR][net.sourceforge.jnlp.tools.JarCertVerifier]
Error in verify jar C:\Users\fke\.cache\icedtea-web\cache\0\8\org.eclipse.swt.win32.win32.x86_64_3.113.0.v20191204-0601.jar
java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:117)
	at net.sourceforge.jnlp.util.JarFile.<init>(JarFile.java:57)
	at net.sourceforge.jnlp.tools.JarCertVerifier.verifyJar(JarCertVerifier.java:272)
	at net.sourceforge.jnlp.tools.JarCertVerifier.verifyJars(JarCertVerifier.java:250)
	at net.sourceforge.jnlp.tools.JarCertVerifier.add(JarCertVerifier.java:224)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.initializeResources(JNLPClassLoader.java:705)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.<init>(JNLPClassLoader.java:350)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.createInstance(JNLPClassLoader.java:423)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.getInstance(JNLPClassLoader.java:495)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.getInstance(JNLPClassLoader.java:468)
	at net.sourceforge.jnlp.Launcher.createApplication(Launcher.java:579)
	at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:372)
	at net.sourceforge.jnlp.Launcher.access$200(Launcher.java:70)
	at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:654)
[ITW-CORE][2021-03-01 11:53:09.815 MEZ][ERROR][net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader]
Exception while verifying jars
java.lang.RuntimeException: Error in verify jar C:\Users\fke\.cache\icedtea-web\cache\0\8\org.eclipse.swt.win32.win32.x86_64_3.113.0.v20191204-0601.jar
	at net.sourceforge.jnlp.tools.JarCertVerifier.verifyJar(JarCertVerifier.java:292)
	at net.sourceforge.jnlp.tools.JarCertVerifier.verifyJars(JarCertVerifier.java:250)
	at net.sourceforge.jnlp.tools.JarCertVerifier.add(JarCertVerifier.java:224)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.initializeResources(JNLPClassLoader.java:705)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.<init>(JNLPClassLoader.java:350)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.createInstance(JNLPClassLoader.java:423)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.getInstance(JNLPClassLoader.java:495)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.getInstance(JNLPClassLoader.java:468)
	at net.sourceforge.jnlp.Launcher.createApplication(Launcher.java:579)
	at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:372)
	at net.sourceforge.jnlp.Launcher.access$200(Launcher.java:70)
	at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:654)
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:117)
	at net.sourceforge.jnlp.util.JarFile.<init>(JarFile.java:57)
	at net.sourceforge.jnlp.tools.JarCertVerifier.verifyJar(JarCertVerifier.java:272)
	... 11 more
[ITW-CORE][2021-03-01 11:53:09.816 MEZ][ERROR][net.sourceforge.jnlp.AbstractLaunchHandler]
netx: Initialization Error: Could not initialize application. (Fatal: Initialization Error: A fatal error occurred while trying to verify jars. An exception has been thrown in class JarCertVerifier. Being unable to read the cacerts or trusted.certs files could be a possible cause for this exception.: Error in verify jar C:\Users\fke\.cache\icedtea-web\cache\0\8\org.eclipse.swt.win32.win32.x86_64_3.113.0.v20191204-0601.jar)
net.sourceforge.jnlp.LaunchException: Fatal: Initialization Error: Could not initialize application. The application has not been initialized, for more information execute javaws from the command line.
	at net.sourceforge.jnlp.Launcher.createApplication(Launcher.java:587)
	at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:372)
	at net.sourceforge.jnlp.Launcher.access$200(Launcher.java:70)
	at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:654)
Caused by: net.sourceforge.jnlp.LaunchException: Fatal: Initialization Error: A fatal error occurred while trying to verify jars. An exception has been thrown in class JarCertVerifier. Being unable to read the cacerts or trusted.certs files could be a possible cause for this exception.: Error in verify jar C:\Users\fke\.cache\icedtea-web\cache\0\8\org.eclipse.swt.win32.win32.x86_64_3.113.0.v20191204-0601.jar
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.initializeResources(JNLPClassLoader.java:712)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.<init>(JNLPClassLoader.java:350)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.createInstance(JNLPClassLoader.java:423)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.getInstance(JNLPClassLoader.java:495)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.getInstance(JNLPClassLoader.java:468)
	at net.sourceforge.jnlp.Launcher.createApplication(Launcher.java:579)
	... 3 more
[ITW-CORE][2021-03-01 11:53:09.817 MEZ][ERROR][net.sourceforge.jnlp.Launcher]
Launch exception
net.sourceforge.jnlp.LaunchException: Fatal: Initialization Error: Could not initialize application. The application has not been initialized, for more information execute javaws from the command line.
	at net.sourceforge.jnlp.Launcher.createApplication(Launcher.java:587)
	at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:372)
	at net.sourceforge.jnlp.Launcher.access$200(Launcher.java:70)
	at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:654)
Caused by: net.sourceforge.jnlp.LaunchException: Fatal: Initialization Error: A fatal error occurred while trying to verify jars. An exception has been thrown in class JarCertVerifier. Being unable to read the cacerts or trusted.certs files could be a possible cause for this exception.: Error in verify jar C:\Users\fke\.cache\icedtea-web\cache\0\8\org.eclipse.swt.win32.win32.x86_64_3.113.0.v20191204-0601.jar
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.initializeResources(JNLPClassLoader.java:712)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.<init>(JNLPClassLoader.java:350)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.createInstance(JNLPClassLoader.java:423)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.getInstance(JNLPClassLoader.java:495)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.getInstance(JNLPClassLoader.java:468)
	at net.sourceforge.jnlp.Launcher.createApplication(Launcher.java:579)
	... 3 more
[ITW-CORE][2021-03-01 11:53:09.817 MEZ][DEBUG][net.sourceforge.jnlp.runtime.JNLPRuntime] Waiting for exception dialog to be closed
[ITW-CORE][2021-03-01 11:53:11.234 MEZ][DEBUG][com.openwebstart.download.ApplicationDownloadIndicator] Closing DownloadServiceListener
```

**Comment by AndreasEhret** [comment]
Currently we do not have the resources to add this issue to the roadmap, but we are happy to help to create a pull request.
