### ISSUE TITLE
Console set to Show Causing Crash in 1.3.3

### ISSUE THREAD

**Issue by hvitcu** [karakun/OpenWebStart#402]
Hi guys,

I checked that this is not an issue on 1.3.2 but definitely is in 1.3.3.
If console logging is set to show then loading hangs as there’s an IOException:

...NetxSecurityThread
Exception while creating lockable file
java.io.IOException: The system cannot find the path specified
              at java.base/java.io.WinNTFileSystem.createFileExclusively(Native Method)
              at java.base/java.io.File.createNewFile(File.java:1026)
              at net.adoptopenjdk.icedteaweb.lockingfile.LockableFile.<init>(LockableFile.java:91)
              at net.adoptopenjdk.icedteaweb.lockingfile.LockableFile.getInstance(LockableFile.java:75)
              at net.adoptopenjdk.icedteaweb.lockingfile.LockingReaderWriter.<init>(LockingReaderWriter.java:62)
              at net.adoptopenjdk.icedteaweb.client.parts.dialogs.security.appletextendedsecurity.impl.UnsignedAppletActionStorageImpl.<init>(UnsignedAppletActionStorageImpl.java:68)
              at net.adoptopenjdk.icedteaweb.client.parts.dialogs.security.appletextendedsecurity.AppletStartupSecuritySettings.getUnsignedAppletActionGlobalStorage(AppletStartupSecuritySettings.java:62)
              at net.adoptopenjdk.icedteaweb.client.parts.dialogs.security.appletextendedsecurity.UnsignedAppletTrustConfirmation.getStoredEntry(UnsignedAppletTrustConfirmation.java:90)
              at net.adoptopenjdk.icedteaweb.client.parts.dialogs.security.remember.RememberDialog.getRememberedState(RememberDialog.java:79)
              at net.adoptopenjdk.icedteaweb.client.parts.dialogs.security.SecurityDialogMessageHandler.handleMessage(SecurityDialogMessageHandler.java:122)
              at net.adoptopenjdk.icedteaweb.client.parts.dialogs.security.SecurityDialogMessageHandler.run(SecurityDialogMessageHandler.java:92)
              at java.base/java.lang.Thread.run(Thread.java:832)

**Comment by sclassen** [comment]
May be a duplicate of #404
