### ISSUE TITLE
1.3.3 fails to start application (on windows)

### ISSUE THREAD

**Issue by rburgst** [karakun/OpenWebStart#414]
in the log I can see the following exception:
```

[ITW-CORE][2021-04-15 06:42:20.941 MESZ][DEBUG][net.adoptopenjdk.icedteaweb.resources.cache.LeastRecentlyUsedCache] Downloading file: http://192.168.2.42:8080/resources/webstart/app-client.jar into: C:\Users\rburgst\.cache\icedtea-web\cache\0\9\app-client.jar
[ITW-CORE][2021-04-15 06:42:24.129 MESZ][DEBUG][net.adoptopenjdk.icedteaweb.resources.ResourceTracker] Download done. Shutting down executor
[ITW-CORE][2021-04-15 06:42:24.129 MESZ][DEBUG][com.openwebstart.download.ApplicationDownloadIndicator] DownloadServiceListener will be disposed
[ITW-CORE][2021-04-15 06:42:25.644 MESZ][DEBUG][com.openwebstart.download.ApplicationDownloadIndicator] Closing DownloadServiceListener
[ITW-APP ][2021-04-15 06:42:26.285 MESZ][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:233)] Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: Event posted on wrong app context : java.awt.event.InvocationEvent[INVOCATION_DEFAULT,runnable=java.awt.Window$1DisposeAction@4af5860e,notifier=java.awt.EventQueue$1AWTInvocationLock@c5d4fd3,catchExceptions=true,when=1618461746097] on dialog0
[ITW-APP ][2021-04-15 06:42:26.707 MESZ][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:233)] 	at java.desktop/sun.awt.SunToolkit.postEvent(SunToolkit.java:424)
[ITW-APP ][2021-04-15 06:42:26.707 MESZ][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:233)] 	at java.desktop/java.awt.SequencedEvent.dispose(SequencedEvent.java:296)
[ITW-APP ][2021-04-15 06:42:26.707 MESZ][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:233)] 	at java.desktop/java.awt.SequencedEvent.dispatch(SequencedEvent.java:205)
[ITW-APP ][2021-04-15 06:42:26.707 MESZ][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:233)] 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
[ITW-APP ][2021-04-15 06:42:26.754 MESZ][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:233)] 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
[ITW-APP ][2021-04-15 06:42:26.754 MESZ][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:233)] 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
[ITW-APP ][2021-04-15 06:42:26.769 MESZ][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:233)] 	at java.base/java.security.AccessController.doPrivileged(Native Method)
[ITW-APP ][2021-04-15 06:42:26.769 MESZ][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:233)] 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
[ITW-APP ][2021-04-15 06:42:26.785 MESZ][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:233)] 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
[ITW-APP ][2021-04-15 06:42:26.785 MESZ][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:233)] 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
[ITW-APP ][2021-04-15 06:42:26.785 MESZ][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:233)] 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
[ITW-APP ][2021-04-15 06:42:26.785 MESZ][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:233)] 	at java.base/java.security.AccessController.doPrivileged(Native Method)
[ITW-APP ][2021-04-15 06:42:26.785 MESZ][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:233)] 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
[ITW-APP ][2021-04-15 06:42:26.785 MESZ][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:233)] 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
[ITW-APP ][2021-04-15 06:42:26.785 MESZ][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:233)] 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
[ITW-APP ][2021-04-15 06:42:26.785 MESZ][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:233)] 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
[ITW-APP ][2021-04-15 06:42:26.785 MESZ][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:233)] 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
[ITW-APP ][2021-04-15 06:42:26.785 MESZ][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:233)] 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
[ITW-APP ][2021-04-15 06:42:26.785 MESZ][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:233)] 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
[ITW-APP ][2021-04-15 06:42:26.785 MESZ][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:233)] 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

The app is using the azul java 11 JDK.

Strangely if I enter the command from the stage 1 log into terminal the app launches: 
```
c:\tools\zulu11\bin\java.exe -Xbootclasspath/a:C:\Users\rburgst\AppData\Local\Programs\OpenWebStart\openwebstart.jar -Dicedtea-web.bin.location=C:\Users\rburgst\AppData\Local\Programs\OpenWebStart\javaws --add-exports=java.base/sun.net.www.protocol.jar=ALL-UNNAMED,java.desktop --add-exports=java.base/jdk.internal.util.jar=ALL-UNNAMED,java.desktop --add-exports=java.base/com.sun.net.ssl.internal.ssl=ALL-UNNAMED,java.desktop --add-reads=java.naming=ALL-UNNAMED,java.desktop --add-exports=java.desktop/sun.awt.X11=ALL-UNNAMED,java.desktop --add-exports=java.desktop/sun.applet=ALL-UNNAMED,java.desktop,jdk.jsobject --add-exports=java.base/sun.security.action=ALL-UNNAMED,java.desktop --add-reads=java.base=ALL-UNNAMED,java.desktop --add-exports=java.base/sun.net.www.protocol.http=ALL-UNNAMED,java.desktop --add-exports=java.naming/com.sun.jndi.toolkit.url=ALL-UNNAMED,java.desktop --add-exports=java.base/sun.security.util=ALL-UNNAMED,java.desktop --add-reads=java.desktop=ALL-UNNAMED,java.naming --add-exports=java.desktop/sun.awt=ALL-UNNAMED,java.desktop --add-exports=java.base/sun.security.x509=ALL-UNNAMED,java.desktop --add-exports=java.desktop/javax.jnlp=ALL-UNNAMED,java.desktop --add-exports=java.base/sun.security.provider=ALL-UNNAMED,java.desktop --add-exports=java.base/sun.security.validator=ALL-UNNAMED,java.desktop net.sourceforge.jnlp.runtime.Boot -Xnofork http://192.168.2.42:8080/server/webstart.jnlp
```

**Comment by rburgst** [comment]
Note that this problem does not appear on Mac OSX (Catalina) 1.3.3 or on version 1.3.2 (windows)

**Comment by sclassen** [comment]
The exception in the log originates from the application and not from OWS (see the start of the line).
Can you give us a full log file of both stage1 and stage2

**Comment by rburgst** [comment]
attached are the logs from 1.3.2 (folder `works`) and 1.3.3 (folder `notwork`). Note that I had to manually redact a few things, but the majority of the log lines are untouched. In order to facilitate comparing, I have removed the initial 
```
[ITW-APP ][2021-04-15 06:42:26.285 MESZ]
```
[openwebstart-1.3.2-vs-1.3.3.zip](https://github.com/karakun/OpenWebStart/files/6320307/openwebstart-1.3.2-vs-1.3.3.zip)

**Comment by sclassen** [comment]
the exception is in an unexpected location of the log.
Can you describe what you see when the application is not working? Are there any error dialogs poping up or is there simply nothing shown?

**Comment by rburgst** [comment]
I can see nothing, the console windows stay open but the application does not show up. However, closing the console windows alone is not enough to get rid off the java tasks, those have to be killed manually via task manager (e.g. if you try to update to the older working 1.3.2).

**Comment by sclassen** [comment]
Thank you, we will have a look at this

**Comment by AndreasEhret** [comment]
there will be a fix for this on 1.4.0, see #420 for the fix

**Comment by rburgst** [comment]
awesome, thanks a lot. Is there an ETA when 1.4.0 will come out?

**Comment by AndreasEhret** [comment]
if everything works as planned within the next two weeks
