### ISSUE TITLE
All mentioned jars in JNLP are not getting downloaded to cache and that leads to Invocation target exception when i tried in OWS 1.3.3

### ISSUE THREAD

**Issue by ganjampk** [karakun/OpenWebStart#424]
Hi,
When i am trying to start application OWS starts downloading the jars mentioned in JNLP to cache, but it is downloading 36 jars out of 150 mentioned in JNLP and that leads to invocation target exception. Please help on this to resolve the issue and what is obstructing to  download the required Jars? 
[2021-05-19_17_10_22.838-ows-stage2.log](https://github.com/karakun/OpenWebStart/files/6508561/2021-05-19_17_10_22.838-ows-stage2.log)
[2021-05-19_17_05_18.322-ows-settings.log](https://github.com/karakun/OpenWebStart/files/6508566/2021-05-19_17_05_18.322-ows-settings.log)

**Comment by sclassen** [comment]
There are many lines like

could not download resource location=http://localhost:8080/PROFTeller-3.1/app/plugins/...

Can you check that all your jars are available on your localhost

**Comment by ganjampk** [comment]
Thanks for response
Yes, all jars are available in mentioned location and able to download if i copy the same url in browser.

**Comment by sclassen** [comment]
Can you contact us on openwebstart@karakun.com so we can give you a pre-release version to try something different.

**Comment by ganjampk** [comment]
Hi,
i am trying with different options in cache configuration and deployment configuration, and progressed on the issue:
Now i am able to see all 150 jars are downloaded in cache but i am seeing below error in log which is obstructing to launch the application. Please find attached log 
[2021-05-28_16_51_33.486-ows-stage2.log](https://github.com/karakun/OpenWebStart/files/6560836/2021-05-28_16_51_33.486-ows-stage2.log)

Deployment configuration:
ows.jvm.manager.vendor.allowFromJnlp=true
deployment.log.stdstreams=false
deployment.javaws.shortcut=NEVER
ows.remote.debug.startSuspended=false
deployment.log=true
ows.install4j.propertyUpdate=1621594852838
deployment.log.file=true
deployment.proxy.type=0
deployment.cache.max.size=0 (tried with both 0 and -1)

Error: 
Error in verify jar C:\Users\e3011633\.cache\icedtea-web\cache\0\5\com.ibm.icu_67.1.0.jar
java.util.zip.ZipException: zip END header not found
	at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1573)
	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1468)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1475)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1280)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1243)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:732)
	at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:841)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:247)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:348)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at net.sourceforge.jnlp.util.JarFile.createDelegate(JarFile.java:96)
	at net.sourceforge.jnlp.util.JarFile.<init>(JarFile.java:88)
	at net.sourceforge.jnlp.util.JarFile.<init>(JarFile.java:82)
	at net.sourceforge.jnlp.tools.JarCertVerifier.verifyJar(JarCertVerifier.java:272)
	at net.sourceforge.jnlp.tools.JarCertVerifier.verifyJars(JarCertVerifier.java:250)
	at net.sourceforge.jnlp.tools.JarCertVerifier.add(JarCertVerifier.java:224)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.initializeResources(JNLPClassLoader.java:706)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.<init>(JNLPClassLoader.java:350)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.createInstance(JNLPClassLoader.java:423)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.getInstance(JNLPClassLoader.java:495)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.getInstance(JNLPClassLoader.java:542)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.initializeExtensions(JNLPClassLoader.java:562)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.<init>(JNLPClassLoader.java:348)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.createInstance(JNLPClassLoader.java:423)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.getInstance(JNLPClassLoader.java:495)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.getInstance(JNLPClassLoader.java:468)
	at net.sourceforge.jnlp.Launcher.createApplication(Launcher.java:579)
	at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:372)
	at net.sourceforge.jnlp.Launcher.access$200(Launcher.java:70)
	at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:654)
[ITW-CORE][2021-05-28 16:53:47.728 IST][ERROR][net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader]
Exception while verifying jars
java.lang.RuntimeException: Error in verify jar C:\Users\e3011633\.cache\icedtea-web\cache\0\5\com.ibm.icu_67.1.0.jar
	at net.sourceforge.jnlp.tools.JarCertVerifier.verifyJar(JarCertVerifier.java:292)
	at net.sourceforge.jnlp.tools.JarCertVerifier.verifyJars(JarCertVerifier.java:250)
	at net.sourceforge.jnlp.tools.JarCertVerifier.add(JarCertVerifier.java:224)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.initializeResources(JNLPClassLoader.java:706)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.<init>(JNLPClassLoader.java:350)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.createInstance(JNLPClassLoader.java:423)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.getInstance(JNLPClassLoader.java:495)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.getInstance(JNLPClassLoader.java:542)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.initializeExtensions(JNLPClassLoader.java:562)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.<init>(JNLPClassLoader.java:348)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.createInstance(JNLPClassLoader.java:423)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.getInstance(JNLPClassLoader.java:495)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.getInstance(JNLPClassLoader.java:468)
	at net.sourceforge.jnlp.Launcher.createApplication(Launcher.java:579)
	at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:372)
	at net.sourceforge.jnlp.Launcher.access$200(Launcher.java:70)

**Comment by sclassen** [comment]
This could be caused by a failed download. Can you simply delete the file `C:\Users\e3011633.cache\icedtea-web\cache\0\5\com.ibm.icu_67.1.0.jar` and re-run the app. It should download it again. Hopefully without errors this time

**Comment by ganjampk** [comment]
i deleted and re-run the application, but this time its throwing error with different jar . i repeated deleting and re-ran application but every time i am getting same below error, though it downloaded full jar successsfully.

net.sourceforge.jnlp.LaunchException: Fatal: Initialization Error: Could not initialize application. The application has not been initialized, for more information execute javaws from the command line.
	at net.sourceforge.jnlp.Launcher.createApplication(Launcher.java:587)
	at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:372)
	at net.sourceforge.jnlp.Launcher.access$200(Launcher.java:70)
	at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:654)
Caused by: java.lang.RuntimeException: java.lang.Exception: Exception while initializing extension 'http://localhost:8080/PROFTeller-3.0/app/features/com.fnis.pd.teller.wrapper_2.0.0.jnlp'
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.initializeExtensions(JNLPClassLoader.java:572)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.<init>(JNLPClassLoader.java:348)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.createInstance(JNLPClassLoader.java:423)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.getInstance(JNLPClassLoader.java:495)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.getInstance(JNLPClassLoader.java:468)
	at net.sourceforge.jnlp.Launcher.createApplication(Launcher.java:579)
	... 3 more
Caused by: java.lang.Exception: Exception while initializing extension 'http://localhost:8080/PROFTeller-3.0/app/features/com.fnis.pd.teller.wrapper_2.0.0.jnlp'
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.initializeExtensions(JNLPClassLoader.java:565)
	... 8 more
Caused by: net.sourceforge.jnlp.LaunchException: Fatal: Initialization Error: A fatal error occurred while trying to verify jars. An exception has been thrown in class JarCertVerifier. Being unable to read the cacerts or trusted.certs files could be a possible cause for this exception.: Error in verify jar C:\Users\e3011633\.cache\icedtea-web\cache\0\34\org.eclipse.core.commands_3.9.800.v20201021-1339.jar
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.initializeResources(JNLPClassLoader.java:713)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.<init>(JNLPClassLoader.java:350)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.createInstance(JNLPClassLoader.java:423)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.getInstance(JNLPClassLoader.java:495)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.getInstance(JNLPClassLoader.java:542)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.initializeExtensions(JNLPClassLoader.java:562)
	... 8 more

**Comment by ganjampk** [comment]
i tried re-ran the application but every time it is ended up with different jar error and i am seeing below error in the logs. i tried with different options which i got while googled but every time i am ending with different jars.
[2021-06-01_18_03_19.685-ows-stage2.log](https://github.com/karakun/OpenWebStart/files/6585025/2021-06-01_18_03_19.685-ows-stage2.log)
[2021-06-01_18_07_03.20-ows-stage2.log](https://github.com/karakun/OpenWebStart/files/6585029/2021-06-01_18_07_03.20-ows-stage2.log)
[2021-06-02_18_08_49.166-ows-stage2.log](https://github.com/karakun/OpenWebStart/files/6585032/2021-06-02_18_08_49.166-ows-stage2.log)
[2021-06-02_18_50_11.343-ows-stage2.log](https://github.com/karakun/OpenWebStart/files/6585039/2021-06-02_18_50_11.343-ows-stage2.log)





java.util.zip.ZipException: zip END header not found
	at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1573)
	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1468)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1475)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1280)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1243)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:732)
	at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:841)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:247)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:348)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at net.sourceforge.jnlp.util.JarFile.createDelegate(JarFile.java:96)
	at net.sourceforge.jnlp.util.JarFile.<init>(JarFile.java:88)
	at net.sourceforge.jnlp.util.JarFile.<init>(JarFile.java:82)
	at net.sourceforge.jnlp.tools.JarCertVerifier.verifyJar(JarCertVerifier.java:272)
	at net.sourceforge.jnlp.tools.JarCertVerifier.verifyJars(JarCertVerifier.java:250)
	at net.sourceforge.jnlp.tools.JarCertVerifier.add(JarCertVerifier.java:224)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.initializeResources(JNLPClassLoader.java:706)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.<init>(JNLPClassLoader.java:350)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.createInstance(JNLPClassLoader.java:423)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.getInstance(JNLPClassLoader.java:495)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.getInstance(JNLPClassLoader.java:542)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.initializeExtensions(JNLPClassLoader.java:562)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.<init>(JNLPClassLoader.java:348)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.createInstance(JNLPClassLoader.java:423)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.getInstance(JNLPClassLoader.java:495)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.getInstance(JNLPClassLoader.java:468)
	at net.sourceforge.jnlp.Launcher.createApplication(Launcher.java:579)
	at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:372)
	at net.sourceforge.jnlp.Launcher.access$200(Launcher.java:70)
	at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:654)
[ITW-CORE][2021-06-02 18:11:18.249 IST][ERROR][net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader]
Exception while verifying jars
java.lang.RuntimeException: Error in verify jar C:\Users\e3011633\.cache\icedtea-web\cache\0\7\com.ibm.db2_9.5.2.jar
	at net.sourceforge.jnlp.tools.JarCertVerifier.verifyJar(JarCertVerifier.java:292)
	at net.sourceforge.jnlp.tools.JarCertVerifier.verifyJars(JarCertVerifier.java:250)
	at net.sourceforge.jnlp.tools.JarCertVerifier.add(JarCertVerifier.java:224)

**Comment by janakmulani** [comment]
@ganjampk  Can you please try with OWS v 1.4.0?

**Comment by ganjampk** [comment]
i tried and repeated all steps with 1.4.0 as well, but still i am getting same issue as reported earlier.

**Comment by janakmulani** [comment]
@ganjampk Ok please run it with OWS 1.4.0 after deleteing contents of the <User Home>/.cache/icedtea-web/cache directory. Send us the logs at openwebstart@karakun.com.

**Comment by janakmulani** [comment]
Can you please send us your jnlp? Also can you provide a sample app that can reproduce this error?

**Comment by truongts21** [comment]
Hi,
I also got the same error like this, is this problem solved?
Where does the cause come from?
