### ISSUE TITLE
net.sourceforge.jnlp.runtime.JNLPPolicy Error when username contain a space there is a exception when building URI

### ISSUE THREAD

**Issue by alslw** [karakun/OpenWebStart#437]
Hi
   We install OpenWebStart 1.3.3 on Windows 10 (64bits) by user that have username contain white space(username=test user). We try to launch our jar from jnlp file by OpenWebStart launcher and found error message "java.net.URISyntaxException: Illegal character in path at index 20: file://C:/Users/test user/.config/icedtea-web/security/java.policy" in ows-stage1.log and ows-stage2.log, please see this error in below:

[ITW-CORE][2021-07-15 11:47:19.307 UTC][INFO ][net.sourceforge.jnlp.runtime.EnvironmentPrinter] OS: Windows 10
[ITW-CORE][2021-07-15 11:47:19.307 UTC][INFO ][net.sourceforge.jnlp.runtime.EnvironmentPrinter] Java Runtime AdoptOpenJDK-1.8.0_265
[ITW-CORE][2021-07-15 11:47:19.307 UTC][DEBUG][net.sourceforge.jnlp.runtime.JNLPRuntime] using com.openwebstart.extensionpoint.OwsExtensionPoint extension point
[ITW-CORE][2021-07-15 11:47:19.525 UTC][ERROR][net.sourceforge.jnlp.runtime.JNLPPolicy]
ERROR
java.net.URISyntaxException: Illegal character in path at index 20: file://C:/Users/test user/.config/icedtea-web/security/java.policy
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parseHierarchical(URI.java:3105)
	at java.net.URI$Parser.parse(URI.java:3053)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URL.toURI(URL.java:964)
	at net.sourceforge.jnlp.runtime.JNLPPolicy.getPolicyFromUrl(JNLPPolicy.java:238)
	at net.sourceforge.jnlp.runtime.JNLPPolicy.<init>(JNLPPolicy.java:95)
	at net.sourceforge.jnlp.runtime.JNLPRuntime.initialize(JNLPRuntime.java:259)
	at net.sourceforge.jnlp.runtime.Boot.runMain(Boot.java:258)
	at net.sourceforge.jnlp.runtime.Boot.mainWithReturnCode(Boot.java:132)
	at net.sourceforge.jnlp.runtime.Boot.main(Boot.java:114)
	at com.openwebstart.launcher.PhaseTwoWebStartLauncher.main(PhaseTwoWebStartLauncher.java:81)
	at com.openwebstart.launcher.OpenWebStartLauncher.main(OpenWebStartLauncher.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)
	at com.install4j.runtime.launcher.WinLauncher.main(WinLauncher.java:25)

We don't see file "C:/Users/test user/.config/icedtea-web/security/java.policy" in our home user directory but It can launch our jar but we don't know what is affect from this error. **Could you advise this ?**

**Comment by alslw** [comment]
Hi
     We don't see file "C:/Users/test user/.config/icedtea-web/security/java.policy" when we found this error. 
It means OpenWebStart don't use java policy configuration file to process. **Could you confirm this ?**

**Comment by sclassen** [comment]
The error should not have any impact on the application.
Never the less the following PR should fix the displaying of the error

https://github.com/AdoptOpenJDK/IcedTea-Web/pull/813
