### ISSUE TITLE
On a Windows System that disallows Registry Queries via "reg", using the System Proxy will fail

### ISSUE THREAD

**Issue by in-fke** [karakun/OpenWebStart#444]
System is restricted:
```
reg query HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings
FEHLER: Die Registrierungsbearbeitung wurde vom Administrator deaktiviert.
```

OWS with "System Proxy"
```
java.lang.RuntimeException: failed to execute reg binary
	at com.openwebstart.proxy.windows.registry.RegistryQuery.getAllValuesForKey(RegistryQuery.java:23)
	at com.openwebstart.proxy.windows.WindowsProxyProvider.<init>(WindowsProxyProvider.java:19)
	at com.openwebstart.proxy.ProxyProviderType$5.createProvider(ProxyProviderType.java:84)
	at com.openwebstart.proxy.WebStartProxySelector.createProvider(WebStartProxySelector.java:40)
	at com.openwebstart.proxy.WebStartProxySelector.<init>(WebStartProxySelector.java:27)
	at com.openwebstart.extensionpoint.OwsExtensionPoint.createProxySelector(OwsExtensionPoint.java:53)
	at net.sourceforge.jnlp.runtime.JNLPRuntime.initialize(JNLPRuntime.java:289)
```

I wonder if it where avoidable to run "reg" in order to use "system proxy" ?
see https://stackoverflow.com/questions/376101/setting-jvm-jre-to-use-windows-proxy-automatically

Somewhere around here:
https://github.com/karakun/OpenWebStart/blob/master/openwebstart/src/main/java/com/openwebstart/proxy/windows/WindowsProxyProvider.java
https://github.com/karakun/OpenWebStart/blob/40804db8fcf11205281b68c72f935fe1a3b77033/openwebstart/src/main/java/com/openwebstart/proxy/windows/WindowsProxyUtils.java

**Comment by janakmulani** [comment]
@in-fke  We will investigate and come back to you.

**Comment by janakmulani** [comment]
@in-fke  I can reproduce this. I have tried the solution you have suggested. We will try to fix this in a future release.

**Comment by janakmulani** [comment]
See https://github.com/karakun/OpenWebStart/pull/456
