### ISSUE TITLE
java.lang.IllegalArgumentException: '1.8.*' is not a valid version-string according to JSR-56, Appendix A

### ISSUE THREAD

**Issue by csottile** [karakun/OpenWebStart#453]
Hi 
We ecounterd the same problem described in issue #60 , but on a third party jnlp. 

I understand my JNLP is out of standard, but I don't understand why it works on Oracle JWS.

How can we solve? Is there any workaround?

Logs:
```
[ITW-CORE][2021-09-16 14:58:52.709 CEST][ERROR][net.sourceforge.jnlp.JNLPFile]
ERROR
java.lang.IllegalArgumentException: '1.8.*' is not a valid version-string according to JSR-56, Appendix A.
	at net.adoptopenjdk.icedteaweb.jnlp.version.VersionString.fromString(VersionString.java:68)
	at net.sourceforge.jnlp.Parser.getVersionString(Parser.java:1216)
	at net.sourceforge.jnlp.Parser.getJRE(Parser.java:494)
	at net.sourceforge.jnlp.Parser.getResourcesDesc(Parser.java:444)
	at net.sourceforge.jnlp.Parser.getResources(Parser.java:403)
	at net.sourceforge.jnlp.JNLPFile.parse(JNLPFile.java:739)
	at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:252)
	at net.sourceforge.jnlp.JNLPFileFactory.create(JNLPFileFactory.java:80)
	at net.sourceforge.jnlp.JNLPFileFactory.create(JNLPFileFactory.java:63)
	at net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:299)
	at net.sourceforge.jnlp.Launcher.launch(Launcher.java:191)
	at net.sourceforge.jnlp.runtime.Boot.launch(Boot.java:355)
	at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:335)
	at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:73)
	at java.security.AccessController.doPrivileged(Native Method)
	at net.sourceforge.jnlp.runtime.Boot.runMain(Boot.java:279)
	at net.sourceforge.jnlp.runtime.Boot.mainWithReturnCode(Boot.java:132)
	at net.sourceforge.jnlp.runtime.Boot.main(Boot.java:114)
	at com.openwebstart.launcher.PhaseTwoWebStartLauncher.main(PhaseTwoWebStartLauncher.java:86)
	at com.openwebstart.launcher.OpenWebStartLauncher.main(OpenWebStartLauncher.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)
	at com.install4j.runtime.launcher.WinLauncher.main(WinLauncher.java:25)
[ITW-CORE][2021-09-16 14:58:52.712 CEST][ERROR][net.sourceforge.jnlp.AbstractLaunchHandler]
```

I look forward to your kind feedback.

Best regards,
Carmelo

**Comment by sclassen** [comment]
The is no workaround. The specification says the `1.8.*` is not valid.
It therefore also does not specify how this value could be interpreted.

The only thing I can think of is changing the version string in the JNLP.
