### ISSUE TITLE
Cannot launch Mirth Connect with OpenWebStart

### ISSUE THREAD

**Issue by jonbartels** [karakun/OpenWebStart#481]
There are several users of Mirth Connect (https://github.com/nextgenhealthcare/connect) trying to use OpenWebStart to launch that application.

I am running MacOS Catalina 10.15.7 and OWS 1.5.0 . 

I consistently get an error:
```
[ITW-CORE][2021-12-08 16:28:18.204 EST][DEBUG][net.sourceforge.jnlp.runtime.CachedJarFileCallback] Class-Path attribute cleared for /Users/jon.bartels/.cache/icedtea-web/cache/0/136/mirth-client.jar
[ITW-CORE][2021-12-08 16:28:26.836 EST][DEBUG][net.sourceforge.jnlp.runtime.CachedJarFileCallback] Class-Path attribute cleared for /Users/jon.bartels/.cache/icedtea-web/cache/0/146/httpclient-4.5.11.jar
[ITW-CORE][2021-12-08 16:28:26.990 EST][DEBUG][net.sourceforge.jnlp.runtime.CachedJarFileCallback] Class-Path attribute cleared for /Users/jon.bartels/.cache/icedtea-web/cache/0/138/mirth-client-core.jar
[ITW-APP ][2021-12-08 16:28:27.077 EST][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:242)] java.lang.IllegalStateException: zip file closed
[ITW-APP ][2021-12-08 16:28:27.077 EST][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:242)]   at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:823)
[ITW-APP ][2021-12-08 16:28:27.077 EST][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:242)]   at java.base/java.util.zip.ZipFile.jarEntries(ZipFile.java:529)
[ITW-APP ][2021-12-08 16:28:27.077 EST][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:242)]   at java.base/java.util.zip.ZipFile$1.entries(ZipFile.java:1084)
```

To the best of my ability, this does not tell me what file or inputstream it was trying to read. Is there any means to discover what the issue is?

Historically, Mirth Connect is known to be sensitive to the presence of JavaFX. The "Launcher" tool from NextGen ships with Oracle Java 8. Other Mirth Connect related projects are known to use Corretto and Zulu because those ship with JavaFX.

I also wonder if this is a permissions issue. Do I have to grant applications executed with OWS permission to open network connections?

If you are not familiar with Mirth Connect you can reproduce this problem with:

1. Get the MC tarball from https://github.com/nextgenhealthcare/connect/releases
2. Unpack the tarball and launch `./mcserver` (this launches the service without backgrounding the process, it will use a local Derby database. No other config is needed)
3. Point a browser or OpenWebStart at `http://localhost:8080/webstart.jnlp` and launch the app
4. Watch the OpenWebStart logs or console.
5. You can log in to the application with the username `admin` and the password `admin`
6. After entering credentials you will see this error from OWS. The login panel will error that it cannot connect to Mirth Connect

**Comment by jonbartels** [comment]
I am marking this issue as closed. Thank you for replying that this is internal to Mirth Connect and not an issue with OWS.
