### ISSUE TITLE
version 1.5: -about does not work while -about --headless does

### ISSUE THREAD

**Issue by elbosso** [karakun/OpenWebStart#483]
There is an exception thrown when starting
```
javaws -about
```
on (`uname -a`)
```
Linux tichy 5.11.0-43-generic #47~20.04.2-Ubuntu SMP Mon Dec 13 11:06:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
Exception:
```
[ITW-CORE][2021-12-30 07:35:07.569 CET][ERROR][net.adoptopenjdk.icedteaweb.client.parts.about.HTMLPanel]
ERROR
java.io.IOException: invalid url
        at javax.swing.JEditorPane.setPage(JEditorPane.java:415)
        at javax.swing.JEditorPane.<init>(JEditorPane.java:261)
        at net.adoptopenjdk.icedteaweb.client.parts.about.HTMLPanel.<init>(HTMLPanel.java:62)
        at net.adoptopenjdk.icedteaweb.client.parts.about.AboutDialog.actionPerformed(AboutDialog.java:163)
        at net.adoptopenjdk.icedteaweb.client.parts.about.AboutDialog.<init>(AboutDialog.java:124)
        at net.adoptopenjdk.icedteaweb.client.parts.about.AboutDialog.display(AboutDialog.java:271)
        at net.adoptopenjdk.icedteaweb.client.parts.about.AboutDialog.display(AboutDialog.java:267)
        at net.adoptopenjdk.icedteaweb.client.parts.about.AboutDialog.display(AboutDialog.java:263)
        at net.sourceforge.jnlp.runtime.Boot.runMain(Boot.java:209)
        at net.sourceforge.jnlp.runtime.Boot.mainWithReturnCode(Boot.java:132)
        at net.sourceforge.jnlp.runtime.Boot.main(Boot.java:114)
        at com.openwebstart.launcher.PhaseTwoWebStartLauncher.main(PhaseTwoWebStartLauncher.java:86)
        at com.openwebstart.launcher.OpenWebStartLauncher.main(OpenWebStartLauncher.java:45)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
        at com.install4j.runtime.launcher.UnixLauncher.start(UnixLauncher.java:66)
        at install4j.com.openwebstart.launcher.OpenWebStartLauncher.main(Unknown Source)
```

**Comment by janakmulani** [comment]
-about option is not implemented. You can use itw-settings.exe. 

What is your reason behind using -about argument with javaws. 

Which other commandline arguments (like -about, -viewer) would you like to be supported by OWS?
