### ISSUE TITLE
Can not open OWS v1.5.1 at all 

### ISSUE THREAD

**Issue by faris-shi** [karakun/OpenWebStart#492]
I installed OWS for our customers, but find OWS does not works.

blew is error log when I open the Open Web Start Setting.

```
[pos][ITW-CORE][2022-01-28 17:30:33.995 EST][INFO ][net.sourceforge.jnlp.util.logging.filelogs.WriterBasedFileLog][Output controller consumer daemon#e536135] writer-based impl.
[ITW-CORE][2022-01-28 17:30:33.771 EST][DEBUG][net.adoptopenjdk.icedteaweb.logging.LoggerFactory] init logger factory to net.sourceforge.jnlp.util.logging.OutputControllerLoggerFactory@3581c5f3
[ITW-CORE][2022-01-28 17:30:33.778 EST][INFO ][net.sourceforge.jnlp.runtime.EnvironmentPrinter] OpenWebStartLauncher called with args: [].
[ITW-CORE][2022-01-28 17:30:33.779 EST][INFO ][net.sourceforge.jnlp.runtime.EnvironmentPrinter] OS: Windows 10
[ITW-CORE][2022-01-28 17:30:33.779 EST][INFO ][net.sourceforge.jnlp.runtime.EnvironmentPrinter] Java Runtime Temurin-1.8.0_312
[ITW-CORE][2022-01-28 17:30:33.860 EST][INFO ][com.openwebstart.launcher.ControlPanelLauncher] Starting OpenWebStart ControlPanel 1.5.1
[ITW-CORE][2022-01-28 17:30:33.907 EST][INFO ][net.sourceforge.jnlp.config.DeploymentConfiguration] Ico provider registered correctly.
[ITW-CORE][2022-01-28 17:30:33.942 EST][INFO ][net.sourceforge.jnlp.config.DeploymentConfiguration] Ico provider registered correctly.
[ITW-CORE][2022-01-28 17:30:33.945 EST][INFO ][net.sourceforge.jnlp.config.DeploymentConfiguration] Loading USER level properties from: file:/C:/Users/pos/.config/icedtea-web/deployment.properties
[ITW-CORE][2022-01-28 17:30:33.996 EST][DEBUG][net.sourceforge.jnlp.util.logging.FileLog] Start logging into: net.sourceforge.jnlp.util.logging.filelogs.WriterBasedFileLog@5ab34714
[ITW-CORE][2022-01-28 17:30:33.993 EST][INFO ][net.sourceforge.jnlp.config.DeploymentConfiguration] Loading USER level properties from: file:/C:/Users/pos/.config/icedtea-web/deployment.properties
[ITW-CORE][2022-01-28 17:30:34.032 EST][DEBUG][com.openwebstart.launcher.InitialConfigurationCheck] Checking if installation time (1643408049693) is after last initial config time (1643408055282)
[ITW-CORE][2022-01-28 17:30:34.063 EST][DEBUG][net.sourceforge.jnlp.runtime.JNLPRuntime] Trying to set download indicator
[ITW-CORE][2022-01-28 17:30:34.064 EST][DEBUG][net.sourceforge.jnlp.runtime.JNLPRuntime] Setting download indicator to com.openwebstart.download.ApplicationDownloadIndicator@704921a5
[ITW-CORE][2022-01-28 17:30:34.107 EST][DEBUG][net.sourceforge.jnlp.runtime.JNLPRuntime] using com.openwebstart.extensionpoint.OwsExtensionPoint extension point
[ITW-CORE][2022-01-28 17:30:34.278 EST][DEBUG][net.adoptopenjdk.icedteaweb.client.controlpanel.ControlPanel] Adding view RuntimeManagerPanel to control panel
[ITW-CORE][2022-01-28 17:30:34.279 EST][DEBUG][net.adoptopenjdk.icedteaweb.client.controlpanel.ControlPanel] Adding view UpdatePanel to control panel
[ITW-CORE][2022-01-28 17:30:34.280 EST][DEBUG][net.adoptopenjdk.icedteaweb.client.controlpanel.ControlPanel] Adding view OpenWebStartAboutPanel to control panel
[ITW-CORE][2022-01-28 17:30:34.280 EST][DEBUG][net.adoptopenjdk.icedteaweb.client.controlpanel.ControlPanel] Adding view SimpleDesktopSettingsPanel to control panel
[ITW-CORE][2022-01-28 17:30:34.281 EST][DEBUG][net.adoptopenjdk.icedteaweb.client.controlpanel.ControlPanel] Won't add view ApplicationManagerPanel to control panel since it is deactivated
[ITW-CORE][2022-01-28 17:30:34.282 EST][DEBUG][net.adoptopenjdk.icedteaweb.client.controlpanel.ControlPanel] Adding view Logging to control panel
[ITW-CORE][2022-01-28 17:30:34.283 EST][DEBUG][net.adoptopenjdk.icedteaweb.client.controlpanel.ControlPanel] Adding view ProxyConfig to control panel
[ITW-CORE][2022-01-28 17:30:34.284 EST][DEBUG][net.adoptopenjdk.icedteaweb.client.controlpanel.ControlPanel] Adding view DebugOptions to control panel
[ITW-CORE][2022-01-28 17:30:34.285 EST][DEBUG][net.adoptopenjdk.icedteaweb.client.controlpanel.ControlPanel] Won't add view DebuggingPanel to control panel since it is deactivated
[ITW-CORE][2022-01-28 17:30:34.286 EST][DEBUG][net.adoptopenjdk.icedteaweb.client.controlpanel.ControlPanel] Won't add view DesktopShortcutPanel to control panel since it is deactivated
[ITW-CORE][2022-01-28 17:30:34.299 EST][DEBUG][net.adoptopenjdk.icedteaweb.client.controlpanel.ControlPanel] Won't add view JVMPanel to control panel since it is deactivated
[ITW-CORE][2022-01-28 17:30:34.300 EST][DEBUG][net.adoptopenjdk.icedteaweb.client.controlpanel.ControlPanel] Won't add view NetworkSettingsPanel to control panel since it is deactivated
[ITW-CORE][2022-01-28 17:30:34.300 EST][DEBUG][net.adoptopenjdk.icedteaweb.client.controlpanel.ControlPanel] Won't add view PolicyPanel to control panel since it is deactivated
[ITW-CORE][2022-01-28 17:30:34.301 EST][DEBUG][net.adoptopenjdk.icedteaweb.client.controlpanel.ControlPanel] Adding view SecuritySettingsPanel to control panel
[ITW-CORE][2022-01-28 17:30:34.302 EST][DEBUG][net.adoptopenjdk.icedteaweb.client.controlpanel.ControlPanel] Won't add view UnsignedAppletsTrustingListPanel to control panel since it is deactivated
[ITW-CORE][2022-01-28 17:30:34.303 EST][DEBUG][net.adoptopenjdk.icedteaweb.client.controlpanel.ControlPanel] Won't add view AboutPanel to control panel since it is deactivated
[ITW-CORE][2022-01-28 17:30:34.304 EST][DEBUG][net.adoptopenjdk.icedteaweb.client.controlpanel.ControlPanel] Adding view TemporaryInternetFilesPanel to control panel
[ITW-CORE][2022-01-28 17:30:34.305 EST][DEBUG][net.adoptopenjdk.icedteaweb.client.controlpanel.ControlPanel] Adding view CertificatePane to control panel
[ITW-CORE][2022-01-28 17:30:34.305 EST][DEBUG][net.adoptopenjdk.icedteaweb.client.controlpanel.ControlPanel] Adding view ServerWhitelistPanel to control panel
[ITW-CORE][2022-01-28 17:30:34.418 EST][DEBUG][com.openwebstart.jvm.LocalRuntimeManager] Loading runtime cache from filesystem
[ITW-CORE][2022-01-28 17:30:34.418 EST][DEBUG][com.openwebstart.jvm.LocalRuntimeManager] Clearing runtime cache
[ITW-APP ][2022-01-28 17:30:34.470 EST][ERROR][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] Exception in thread "AWT-EventQueue-0" com.openwebstart.google.gson.JsonSyntaxException: Error in JSON conversion
[ITW-APP ][2022-01-28 17:30:34.470 EST][ERROR][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] 	at com.openwebstart.jvm.json.JsonHandler.fromJson(JsonHandler.java:36)
[ITW-APP ][2022-01-28 17:30:34.470 EST][ERROR][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] 	at com.openwebstart.jvm.LocalRuntimeManager.loadRuntimes(LocalRuntimeManager.java:147)
[ITW-APP ][2022-01-28 17:30:34.470 EST][ERROR][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] 	at com.openwebstart.jvm.JavaRuntimeManager.reloadLocalRuntimes(JavaRuntimeManager.java:51)
[ITW-APP ][2022-01-28 17:30:34.471 EST][ERROR][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] 	at com.openwebstart.jvm.ui.RuntimeManagerPanel.<init>(RuntimeManagerPanel.java:54)
[ITW-APP ][2022-01-28 17:30:34.471 EST][ERROR][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] 	at com.openwebstart.jvm.ui.RuntimeManagerPanelProvider.createPanel(RuntimeManagerPanelProvider.java:28)
[ITW-APP ][2022-01-28 17:30:34.471 EST][ERROR][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] 	at net.adoptopenjdk.icedteaweb.client.controlpanel.ControlPanel.lambda$createMainSettingsPanel$4(ControlPanel.java:213)
[ITW-APP ][2022-01-28 17:30:34.471 EST][ERROR][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] 	at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1321)
[ITW-APP ][2022-01-28 17:30:34.472 EST][ERROR][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] 	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
[ITW-APP ][2022-01-28 17:30:34.472 EST][ERROR][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] 	at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
[ITW-APP ][2022-01-28 17:30:34.472 EST][ERROR][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:483)
[ITW-APP ][2022-01-28 17:30:34.472 EST][ERROR][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
[ITW-APP ][2022-01-28 17:30:34.472 EST][ERROR][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
[ITW-APP ][2022-01-28 17:30:34.473 EST][ERROR][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[ITW-APP ][2022-01-28 17:30:34.473 EST][ERROR][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] 	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
[ITW-APP ][2022-01-28 17:30:34.473 EST][ERROR][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] 	at net.adoptopenjdk.icedteaweb.client.controlpanel.ControlPanel.createMainSettingsPanel(ControlPanel.java:213)
[ITW-APP ][2022-01-28 17:30:34.473 EST][ERROR][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] 	at net.adoptopenjdk.icedteaweb.client.controlpanel.ControlPanel.<init>(ControlPanel.java:100)
[ITW-APP ][2022-01-28 17:30:34.473 EST][ERROR][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] 	at com.openwebstart.launcher.ControlPanelLauncher.lambda$main$2(ControlPanelLauncher.java:81)
[ITW-APP ][2022-01-28 17:30:34.474 EST][ERROR][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] 	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
[ITW-APP ][2022-01-28 17:30:34.474 EST][ERROR][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
[ITW-APP ][2022-01-28 17:30:34.474 EST][ERROR][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] 	at java.awt.EventQueue.access$500(EventQueue.java:97)
[ITW-APP ][2022-01-28 17:30:34.474 EST][ERROR][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] 	at java.awt.EventQueue$3.run(EventQueue.java:709)
[ITW-APP ][2022-01-28 17:30:34.474 EST][ERROR][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] 	at java.awt.EventQueue$3.run(EventQueue.java:703)
[ITW-APP ][2022-01-28 17:30:34.474 EST][ERROR][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] 	at java.security.AccessController.doPrivileged(Native Method)
[ITW-APP ][2022-01-28 17:30:34.475 EST][ERROR][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
[ITW-APP ][2022-01-28 17:30:34.475 EST][ERROR][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
[ITW-APP ][2022-01-28 17:30:34.475 EST][ERROR][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
[ITW-APP ][2022-01-28 17:30:34.475 EST][ERROR][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
[ITW-APP ][2022-01-28 17:30:34.475 EST][ERROR][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
[ITW-APP ][2022-01-28 17:30:34.475 EST][ERROR][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
[ITW-APP ][2022-01-28 17:30:34.476 EST][ERROR][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
[ITW-APP ][2022-01-28 17:30:34.476 EST][ERROR][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
[ITW-APP ][2022-01-28 17:30:34.476 EST][ERROR][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] Caused by: com.openwebstart.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
[ITW-APP ][2022-01-28 17:30:34.476 EST][ERROR][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] 	at com.openwebstart.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
[ITW-APP ][2022-01-28 17:30:34.477 EST][ERROR][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] 	at com.openwebstart.google.gson.Gson.fromJson(Gson.java:927)
[ITW-APP ][2022-01-28 17:30:34.477 EST][ERROR][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] 	at com.openwebstart.google.gson.Gson.fromJson(Gson.java:892)
[ITW-APP ][2022-01-28 17:30:34.477 EST][ERROR][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] 	at com.openwebstart.google.gson.Gson.fromJson(Gson.java:841)
[ITW-APP ][2022-01-28 17:30:34.477 EST][ERROR][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] 	at com.openwebstart.google.gson.Gson.fromJson(Gson.java:813)
[ITW-APP ][2022-01-28 17:30:34.477 EST][ERROR][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] 	at com.openwebstart.jvm.json.JsonHandler.fromJson(JsonHandler.java:34)
[ITW-APP ][2022-01-28 17:30:34.478 EST][ERROR][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] 	... 30 more
[ITW-APP ][2022-01-28 17:30:34.478 EST][ERROR][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
[ITW-APP ][2022-01-28 17:30:34.478 EST][ERROR][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] 	at com.openwebstart.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
[ITW-APP ][2022-01-28 17:30:34.478 EST][ERROR][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] 	at com.openwebstart.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215)
[ITW-APP ][2022-01-28 17:30:34.478 EST][ERROR][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] 	... 35 more
[ITW-CORE][2022-01-28 17:30:35.483 EST][INFO ][net.sourceforge.jnlp.util.logging.OutputController] Increase polling interval for shutdown phase

```

**Comment by sclassen** [comment]
This looks like a corrupted jvm cache file.
You can find the jvm cache at C:/Users/pos/.cache/icedtea-web

Find the json file and validate its content or delete the entire jvm cache.

Am 29. Januar 2022 01:30:01 MEZ schrieb "Faris.Shi" ***@***.***>:

**Comment by faris-shi** [comment]
@sclassen Thank you very much. It works now.
