### ISSUE TITLE
Tries to use Pack200 even on Java 14+

### ISSUE THREAD

**Issue by lapo-luchini** [karakun/OpenWebStart#499]
It automatically detects and prefers the pack200 URL, but then it chokes on a missing JAR:

```log
[ITW-CORE][2022-02-15 12:23:54.449 CET][DEBUG][net.adoptopenjdk.icedteaweb.lockingfile.LockableFile] Trying to create lock file C:\Users\lapo\.cache\icedtea-web\cache\recently_used.cache.lock
[ITW-CORE][2022-02-15 12:23:54.453 CET][INFO ][net.adoptopenjdk.icedteaweb.resources.cache.CacheImpl] isCached: CacheKey{location=https://w4s.andxor.it/andxor-tablet.jar, version=null} = false
[ITW-CORE][2022-02-15 12:23:54.453 CET][DEBUG][net.adoptopenjdk.icedteaweb.resources.initializer.UnversionedResourceInitializer] Candidate URLs for [l=https://w4s.andxor.it/andxor-tablet.jar v=null s=I]: [https://w4s.andxor.it/andxor-tablet.jar.pack.gz, https://w4s.andxor.it/andxor-tablet.jar]
[ITW-CORE][2022-02-15 12:23:54.456 CET][DEBUG][com.openwebstart.proxy.direct.DirectProxyProvider] Using NO_PROXY
[ITW-CORE][2022-02-15 12:23:54.499 CET][DEBUG][com.openwebstart.proxy.direct.DirectProxyProvider] Using NO_PROXY
[ITW-CORE][2022-02-15 12:23:54.654 CET][DEBUG][net.adoptopenjdk.icedteaweb.resources.initializer.UrlProber] URL connection 'https://w4s.andxor.it/andxor-tablet.jar.pack.gz' header fields: {Accept-Ranges=[bytes], null=[HTTP/1.1 200 OK], Server=[nginx/1.18.0], ETag=[W/"836073-1488555964000"], Connection=[keep-alive], Last-Modified=[Fri, 03 Mar 2017 15:46:04 GMT], Content-Length=[836073], Date=[Tue, 15 Feb 2022 11:23:56 GMT], Content-Type=[application/x-gzip]}
[ITW-CORE][2022-02-15 12:23:54.654 CET][DEBUG][net.adoptopenjdk.icedteaweb.resources.initializer.BaseResourceInitializer] Best url for [l=https://w4s.andxor.it/andxor-tablet.jar v=null s=I] is https://w4s.andxor.it/andxor-tablet.jar.pack.gz by HEAD
[ITW-CORE][2022-02-15 12:23:54.655 CET][DEBUG][net.adoptopenjdk.icedteaweb.resources.initializer.UnversionedResourceInitializer] Found best URL for [l=https://w4s.andxor.it/andxor-tablet.jar v=null s=I]: url:https://w4s.andxor.it/andxor-tablet.jar.pack.gz; responseCode:200; location: null; version: null; lastModified: 1488555964000; contentLength: 836073; 
[ITW-CORE][2022-02-15 12:23:54.661 CET][DEBUG][net.adoptopenjdk.icedteaweb.resources.downloader.BaseResourceDownloader] Will download in background: https://w4s.andxor.it/andxor-tablet.jar.pack.gz
[ITW-CORE][2022-02-15 12:23:54.662 CET][DEBUG][com.openwebstart.proxy.direct.DirectProxyProvider] Using NO_PROXY
[ITW-CORE][2022-02-15 12:23:54.684 CET][DEBUG][net.adoptopenjdk.icedteaweb.lockingfile.LockableFile] Trying to create lock file C:\Users\lapo\.cache\icedtea-web\cache\recently_used.cache.lock
[ITW-CORE][2022-02-15 12:23:54.685 CET][INFO ][net.adoptopenjdk.icedteaweb.resources.cache.CacheImpl] isCached: CacheKey{location=https://w4s.andxor.it/andxor-tablet.jar, version=null} = false
[ITW-CORE][2022-02-15 12:23:54.685 CET][DEBUG][net.adoptopenjdk.icedteaweb.resources.downloader.StreamUnpacker] Will use Pack200 for 'https://w4s.andxor.it/andxor-tablet.jar.pack.gz'
[ITW-APP ][2022-02-15 12:23:54.689 CET][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] Exception in thread "itwpool-1-itwthread-2" java.lang.NoClassDefFoundError: java/util/jar/Pack200
[ITW-APP ][2022-02-15 12:23:54.689 CET][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] 	at net.adoptopenjdk.icedteaweb.resources.downloader.PackGzipUnpacker.unpack(PackGzipUnpacker.java:35)
[ITW-APP ][2022-02-15 12:23:54.689 CET][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] 	at net.adoptopenjdk.icedteaweb.resources.downloader.BaseResourceDownloader.tryDownloading(BaseResourceDownloader.java:184)
[ITW-APP ][2022-02-15 12:23:54.690 CET][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] 	at net.adoptopenjdk.icedteaweb.resources.downloader.BaseResourceDownloader.tryDownloading(BaseResourceDownloader.java:138)
[ITW-APP ][2022-02-15 12:23:54.690 CET][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] 	at net.adoptopenjdk.icedteaweb.resources.downloader.BaseResourceDownloader.lambda$downloadFrom$3(BaseResourceDownloader.java:119)
[ITW-APP ][2022-02-15 12:23:54.690 CET][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[ITW-APP ][2022-02-15 12:23:54.690 CET][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[ITW-APP ][2022-02-15 12:23:54.690 CET][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)] 	at java.base/java.lang.Thread.run(Thread.java:833)
```

This is the JNLP file:
```xml
<?xml version="1.0" encoding="utf-8"?>
<jnlp spec="1.0+">
  <information>
    <title>Andxor Tablet Signature Client</title>
    <vendor>Andxor Soluzioni Informatiche srl</vendor>
    <homepage href="http://www.andxor.it/" />
    <description>Andxor Tablet Signature Client is used by web2sign to access the signature tablet hardware.</description>
  </information>
  <security>
    <all-permissions />
  </security>
  <resources>
    <property name="jnlp.packEnabled" value="true"/>
    <j2se version="1.7+" />
    <jar href="https://w4s.andxor.it/andxor-tablet.jar" />
  </resources>
  <application-desc main-class="com.andxor.tablet.applet.Server">
    <argument>xWcHBfU84dU8ErFJQTOHEL</argument>
    <argument>https://w4s.andxor.it/</argument>
  </application-desc>
</jnlp>
```

**Comment by lapo-luchini** [comment]
Also: in this case the GUI just keeps spinning and spinning, if I didn't open up the console I'd have no indication that the process was already stopped.

![image](https://user-images.githubusercontent.com/420454/154054030-6eedfb8f-0402-43c1-adcd-39dd1ec01ec1.png)

**Comment by lapo-luchini** [comment]
Pack200 is not missing from OpenWebStart but rather from Java17 that it was trying to use.
I tried forcing Java11 and it all works okay.
I think OpenWebStart could, on its side, detect the usage of Java14+ (where Pack200 is missing) and try and prefer the uncompressed JAR instead of the Pack200 compressed one, as both are detected, as per this log line:
`[ITW-CORE][2022-02-15 12:23:54.453 CET][DEBUG][net.adoptopenjdk.icedteaweb.resources.initializer.UnversionedResourceInitializer] Candidate URLs for [l=https://w4s.andxor.it/andxor-tablet.jar v=null s=I]: [https://w4s.andxor.it/andxor-tablet.jar.pack.gz, https://w4s.andxor.it/andxor-tablet.jar]`

**Comment by sclassen** [comment]
Can you post a little more of that log please.
It seams funny that how the exception is logged in your case.

Thanks

**Comment by lapo-luchini** [comment]
Sure, there you go: [log.zip](https://github.com/karakun/OpenWebStart/files/8075282/log.zip)

**Comment by sclassen** [comment]
Thank you, found what I was looking for.

The next planned release is in April. The fix will make it into that

**Comment by janakmulani** [comment]
https://github.com/AdoptOpenJDK/IcedTea-Web/pull/857
