### ISSUE TITLE
Unable to run application with jdk18: The Security Manager is deprecated and will be removed in a future release

### ISSUE THREAD

**Issue by RoarBjur** [karakun/OpenWebStart#508]
When trying to start an application with jdk18, the jnlp fail to start with the following error:
```
[ITW-CORE][2022-03-30 13:21:25.270 CEST][DEBUG][net.sourceforge.jnlp.runtime.Boot]
Exiting Boot.mainWithReturnCode() exceptionally
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
        at java.base/java.lang.System.setSecurityManager(System.java:416)
        at net.sourceforge.jnlp.runtime.JNLPRuntime.initialize(JNLPRuntime.java:266)
        at net.sourceforge.jnlp.runtime.Boot.runMain(Boot.java:258)
        at net.sourceforge.jnlp.runtime.Boot.mainWithReturnCode(Boot.java:132)
        at net.sourceforge.jnlp.runtime.Boot.main(Boot.java:114)
```
(Using version 1.5.2)

The application starts if i use the --nosecurity flag, like this:  "javaws jnlp.jnlp --nosecurity", which bypasses the creation of the security manager. Can i change the jnlp-file in any way to work around this issue?

**Comment by janakmulani** [comment]
We have tested OWS that can start Jnlp apps with Java 17. However, we have not tested with Java 18 yet. I don't know what Java 18 recommends about migrating especially for missing classes like SecurityManager.

**Comment by sbwong** [comment]
The Java 18 deprecation of the SecurityManager can be side-stepped for now by using the " -Djava.security.manager=allow" option when running a Java program from the command line.   Can this be integrated into the OWS launch?

**Comment by janakmulani** [comment]
@sbwong Thanks for posting this. We will do the needful.

**Comment by senare** [comment]
Ill link to a article about this from SNYK ... hope it is oki ?

https://snyk.io/blog/securitymanager-removed-java/?utm_medium=social&utm_source=linkedin-organic&utm_content=securitymanager-removed-java
