### ISSUE TITLE
No Suitable JVM was found to start the application

### ISSUE THREAD

**Issue by kulov** [karakun/OpenWebStart#514]
I am getting error "No Suitable JVM was found to start the application"  trying to run .jnlp file.
[stampitls-vat.jnlp.txt](https://github.com/karakun/OpenWebStart/files/8696121/stampitls-vat.jnlp.txt)

Below is the stack trace from the message screen:

```
java.lang.IllegalStateException: could not find any suitable runtime
	at com.openwebstart.launcher.OwsJvmLauncher.getLocalJavaRuntimeOrExit(OwsJvmLauncher.java:70)
	at com.openwebstart.launcher.OwsJvmLauncher.launchExternal(OwsJvmLauncher.java:121)
	at com.openwebstart.launcher.OwsJvmLauncher.launchExternal(OwsJvmLauncher.java:64)
	at net.sourceforge.jnlp.Launcher.launchExternal(Launcher.java:285)
	at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:366)
	at net.sourceforge.jnlp.Launcher.access$200(Launcher.java:70)
	at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:654)

```

I collected file logging with additional details.
[2022-05-16_00_43_16.743-ows-stage1.log](https://github.com/karakun/OpenWebStart/files/8696119/2022-05-16_00_43_16.743-ows-stage1.log)

The error inside the file is as follows:

```
[ITW-CORE][2022-05-16 00:43:19.622 EEST][ERROR][com.openwebstart.jvm.RemoteRuntimeManager]
Error while trying to find a remote version
java.lang.NullPointerException: Argument 'list' may not be null
	at net.adoptopenjdk.icedteaweb.Assert.requireNonNull(Assert.java:27)
	at com.openwebstart.jvm.util.RemoteRuntimeManagerCache.<init>(RemoteRuntimeManagerCache.java:19)
	at com.openwebstart.jvm.RemoteRuntimeManager.lambda$loadListOfRemoteRuntimes$3(RemoteRuntimeManager.java:82)
	at com.openwebstart.func.Result.lambda$of$1(Result.java:97)
	at java.util.Optional.orElseGet(Optional.java:267)
	at com.openwebstart.jvm.RemoteRuntimeManager.loadListOfRemoteRuntimes(RemoteRuntimeManager.java:77)
	at com.openwebstart.jvm.RemoteRuntimeManager.getBestRuntime(RemoteRuntimeManager.java:59)
	at com.openwebstart.jvm.JavaRuntimeSelector.getJavaRuntime(JavaRuntimeSelector.java:64)
	at com.openwebstart.launcher.OwsJvmLauncher.getJavaRuntime(OwsJvmLauncher.java:103)
	at com.openwebstart.launcher.OwsJvmLauncher.getLocalJavaRuntimeOrExit(OwsJvmLauncher.java:82)
	at com.openwebstart.launcher.OwsJvmLauncher.launchExternal(OwsJvmLauncher.java:136)
	at com.openwebstart.launcher.OwsJvmLauncher.launchExternal(OwsJvmLauncher.java:78)
	at net.sourceforge.jnlp.Launcher.launchExternal(Launcher.java:285)
	at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:366)
	at net.sourceforge.jnlp.Launcher.access$200(Launcher.java:70)
	at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:654)
[ITW-CORE][2022-05-16 00:43:19.625 EEST][DEBUG][com.openwebstart.jvm.JavaRuntimeSelector] No remote runtime found, will check deactivated local runtimes.
```

I was able to workaround the error by downloading Java SE Development Kit 17.0.3.1 from [here](https://www.oracle.com/java/technologies/downloads/#jdk17-windows).
Then I open JVM Manager in OpenWebStart settings and clicked Find local to locate the JDK.

Any idea why the jnlp file does not run out of the box?

**Comment by sclassen** [comment]
Your JNLP specifies a href in the j2se tag which points to a location not compatible with openwebstart.
You can dissable in the settings the usage of href for downloading the jvm. This is recommendet as it is a potential risk to download a jvm from any location found in a jnlp.

Openwebstart has a default location where jvms from Azul, Bellsoft and Adoptium are linked


Am 16. Mai 2022 00:09:53 MESZ schrieb Martin Kulov ***@***.***>:

**Comment by luiscamposflores** [comment]
OpenWebStart is offline today. On first launch it doesn't auto detect any local jvm and fails to find remote jvm:
Trying to find local Java runtime. Requested version: '1.8+' Requested vendor: '*' requested os: 'MAC64' active: 'false'
No remote runtime found, will check deactivated local runtimes.
Error while trying to find a remote version
Using NO_PROXY
Using NO_PROXY
Endpoint to request for Java runtimes: https://download-openwebstart.com/jvms.json

This happens in Mac, Windows, Linux, for java 1.8 and 11. Friday was working perfectly.

The https://download-openwebstart.com/jvms.json file looks valid and it's reachable.

After we add a jvm manually of through "Find local JVM..." it works.

**Comment by sclassen** [comment]
OK, we had an issue with the jvms.json file.
We added entries for the upcoming mac aarch64 support.
This caused parser issues.
We removed the entries and everything should be working again
