### ISSUE TITLE
OpenWebStart not sending keystrokes

### ISSUE THREAD

**Issue by n3gwg** [karakun/OpenWebStart#527]
I am a Computer Scientist and fear there is some sort of bug in OpenWebStart that I cannot put my finger on.

I have an old IBM x3650 M3 server with its own service processor in it and Java/JNLP based remote console interface. To access this remote console one must first authenticate via a web page (so just downloading and trying to run the JNLP will not work, you must authenticate through the web interface of the service processor first). I elected to use Firefox since current versions of Chromium are very hard to use with self signed SSL certificates, which this server also has on its service processor web interface.

I installed the latest (1.7.0) version of OpenWebStart on Debian 11 (also fully updated) and used the latest version of Firefox that comes with Debian 11.

OpenWebStart does download and bring up the remote console interface; however, it does not transmit keystrokes to the server it only shows me output (so if I walk over to the server's keyboard and type things I see the output duplicated on the remote web console OpenWebStart is showing me).

Ironically, if I run Debian 8 (Jessie) and install IcedTea with Firefox and perform the same activity of logging in via the web interface using Firefox and then start the remote web console it works fine. Keystrokes get sent to the web console, output is displayed, and the other utilities (one of particular usefulness mounts a virtual ISO to the server) all work flawlessly.

Thing of it is, I do not want to have a separate virtual machine to just run a web browser for this singular application, I want to use OpenWebStart on any Linux box I have handy (it also had similar issues on a Mac I tried it on). I do not use Windows for anything, so no testing there.

Any guidance or assistance would be appreciated and if my circumstance is indicative of some bugulance, I am interested to help test any fixes or updates you might come up with.

Stuart

**Comment by fpoirotte** [comment]
Hi,

I'm facing the exact same issue with a very similar setup (fully updated Debian 11.6, OpenWebStart 1.7.0).
I'm using OpenWebStart to access a virtual console on an old iDRAC 6 controller (integrated management card for DELL servers).

The symptoms are the same: I can load the JNLP file, JAR files can be downloaded no problem, and the virtual console displays just fine. Only issue is that keystrokes are not sent to the remote host.

In my local terminal, I see the following traceback for each keypress:
```
Exception in thread "AWT-EventQueue-1" java.lang.UnsatisfiedLinkError: 'void com.avocent.kvm.nativekeyboard.NativeKVM.setCursorLocation(long, int, int)'
	at com.avocent.kvm.nativekeyboard.NativeKVM.setCursorLocation(Native Method)
	at com.avocent.kvm.nativekeyboard.f.run(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
I'm guessing the jars are trying to call native code using JNI against a library that's missing on my system.
Any idea on how to debug the issue?

François

**Comment by fpoirotte** [comment]
In my case, I managed to get it working by:

* Manually editing the JNLP to require j2se version "1.8*" (initial value was "1.6+"), to make sure an old JRE is used
* Fixing the login/password that appeared in the JNLP file (initial values were some numbers)
* Attempting to run javaws on the file a first time: this will fail due to the JRE's security settings
* Changing security settings in ~/.cache/icedtea-web/jvm-cache/adoptium_1.8.0.352_x64/jre/lib/security/java.security (since I'm only using OpenWebStart for this particular use case, I disabled most security settings by allowing insecure/obsolete algorithms)
* Running javaws again: the connection now succeeds and I can correctly send keystrokes to the server

This workaround does not work when used with OpenJDK 11 / OpenJDK 17 (as stated previously, the connection will succeed but keystrokes are not sent).
