### ISSUE TITLE
java.lang.IllegalStateException: zip file closed?  compiled by javac 17. 

### ISSUE THREAD

**Issue by linxd** [karakun/OpenWebStart#541]
at java.base/java.lang.Thread.run(Thread.java:833) 
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) 
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) 
    at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343) 
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) 
    at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304) 
    at com.mirth.connect.client.ui.LoginPanel$8.doInBackground(LoginPanel.java:423) 
    at com.mirth.connect.client.ui.LoginPanel$8.doInBackground(LoginPanel.java:430) 
    at com.mirth.connect.client.core.Client.<init>(Client.java:155) 
    at com.mirth.connect.client.core.Client.<init>(Client.java:189) 
    at org.reflections.Reflections.<init>(Reflections.java:143) 
    at org.reflections.Reflections.<init>(Reflections.java:170) 
    at org.reflections.Reflections.<init>(Reflections.java:129) 
    at org.reflections.Reflections.scan(Reflections.java:204) 
    at org.reflections.Reflections.scan(Reflections.java:240) 
    at org.reflections.vfs.ZipDir$1.iterator(ZipDir.java:26) 
    at org.reflections.vfs.ZipDir$1$1.<init>(ZipDir.java:27) 
    at java.base/java.util.jar.JarFile.entries(JarFile.java:530) 
    at java.base/java.util.zip.ZipFile$1.entries(ZipFile.java:1108) 
    at java.base/java.util.zip.ZipFile.jarEntries(ZipFile.java:532) 
    at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:831) 
java.lang.IllegalStateException: zip file closed

**Comment by jonbartels** [comment]
This is similar to, if not the same as https://github.com/karakun/OpenWebStart/issues/481 . The only difference being that linxd has compiled Mirth instead of using pre-built binaries.

**Comment by jonbartels** [comment]
Upstream question is https://github.com/nextgenhealthcare/connect/discussions/5809
