### ISSUE TITLE
Unavailable Service Exception

### ISSUE THREAD

**Issue by kafran** [karakun/OpenWebStart#544]
Hi,

I am trying to run some old gov service available at https://hod.serpro.gov.br/a83016cv/hodcivws/hodcivws.jnlp
I have tried with Java 17.0.7-Adoptium and Java 11.0.15-MS.
I'm getting the following error:

```
[ITW-APP ][2023-06-20 15:19:26.219 BRT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:233)] javax.jnlp.UnavailableServiceException: javax.jnlp.IntegrationService
[ITW-APP ][2023-06-20 15:19:26.220 BRT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:233)] 	at net.sourceforge.jnlp.services.XServiceManagerStub.lookup(XServiceManagerStub.java:107)
[ITW-APP ][2023-06-20 15:19:26.221 BRT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:233)] 	at javax.jnlp.ServiceManager.lookup(ServiceManager.java:25)
[ITW-APP ][2023-06-20 15:19:26.221 BRT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:233)] 	at com.ibm.eNetwork.HOD.cached.wssupport.WSCachedSupporter.recreateShortcut(Unknown Source)
[ITW-APP ][2023-06-20 15:19:26.221 BRT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:233)] 	at com.ibm.eNetwork.HOD.cached.wssupport.WSCachedSupporter.init(Unknown Source)
[ITW-APP ][2023-06-20 15:19:26.221 BRT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:233)] 	at com.ibm.eNetwork.HOD.cached.wssupport.WSCachedSupporter.main(Unknown Source)
[ITW-APP ][2023-06-20 15:19:26.221 BRT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:233)] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ITW-APP ][2023-06-20 15:19:26.221 BRT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:233)] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ITW-APP ][2023-06-20 15:19:26.221 BRT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:233)] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ITW-APP ][2023-06-20 15:19:26.222 BRT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:233)] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ITW-APP ][2023-06-20 15:19:26.222 BRT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:233)] 	at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:406)
[ITW-APP ][2023-06-20 15:19:26.222 BRT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:233)] 	at net.sourceforge.jnlp.Launcher.access$300(Launcher.java:71)
[ITW-APP ][2023-06-20 15:19:26.222 BRT][ERROR][java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:233)] 	at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:660)
```

Is there something I can do from my side? The owner of the service just says to install Java 8 🫠

**Comment by FelixJongleur42** [comment]
Most legacy applications won’t run with Java9 and higher, due to the module system that was introduced. Install Java8 (Corretto for Example), add it to OWS under settings, and disable all higher Java VMs under those settings - when asked to update, decline.
Luckily, your old application will run that way, using Java8.
Might be a feature request to set / override version spec per App in OWS settings (kind of like “compatibility settings”), but that should be another issue.

**Comment by kafran** [comment]
> Most legacy applications won’t run with Java9 and higher, due to the module system that was introduced. Install Java8 (Corretto for Example), add it to OWS under settings, and disable all higher Java VMs under those settings - when asked to update, decline. Luckily, your old application will run that way, using Java8. Might be a feature request to set / override version spec per App in OWS settings (kind of like “compatibility settings”), but that should be another issue.

Thanks. I installed the Corretto 1.8.0_372 through SDKMAN, same error =/

```
[kafran][ITW-CORE][2023-06-20 15:59:12.191 BRT][INFO ][net.sourceforge.jnlp.util.logging.filelogs.WriterBasedFileLog][Output controller consumer daemon#5e80dabd] writer-based impl.
[ITW-CORE][2023-06-20 15:59:12.049 BRT][INFO ][net.sourceforge.jnlp.runtime.EnvironmentPrinter] OpenWebStartLauncher called with args: [-Xnofork, /Users/kafran/Downloads/hodcivws.jnlp].
[ITW-CORE][2023-06-20 15:59:12.049 BRT][INFO ][net.sourceforge.jnlp.runtime.EnvironmentPrinter] OS: Mac OS X
[ITW-CORE][2023-06-20 15:59:12.049 BRT][INFO ][net.sourceforge.jnlp.runtime.EnvironmentPrinter] Java Runtime Amazon.com Inc.-1.8.0_372
[ITW-CORE][2023-06-20 15:59:12.176 BRT][INFO ][net.sourceforge.jnlp.config.DeploymentConfiguration] Ico provider registered correctly.
[ITW-CORE][2023-06-20 15:59:12.186 BRT][INFO ][net.sourceforge.jnlp.config.DeploymentConfiguration] Loading USER level properties from: file:/Users/kafran/.config/icedtea-web/deployment.properties
[ITW-CORE][2023-06-20 15:59:12.354 BRT][INFO ][net.sourceforge.jnlp.runtime.Boot] Proceeding with jnlp
[ITW-CORE][2023-06-20 15:59:12.355 BRT][INFO ][net.sourceforge.jnlp.runtime.Boot] JNLP file location: /Users/kafran/Downloads/hodcivws.jnlp
[ITW-CORE][2023-06-20 15:59:12.364 BRT][INFO ][net.adoptopenjdk.icedteaweb.xmlparser.MalformedXMLParser] Using MalformedXMLParser
[ITW-CORE][2023-06-20 15:59:12.686 BRT][INFO ][net.sourceforge.jnlp.Parser] Homepage: null
[ITW-CORE][2023-06-20 15:59:12.686 BRT][INFO ][net.sourceforge.jnlp.Parser] Description: Host On-Demand
[ITW-CORE][2023-06-20 15:59:12.687 BRT][INFO ][net.sourceforge.jnlp.JNLPFile] Acceptable vendor tag found, contains: IBM Corporation
[ITW-CORE][2023-06-20 15:59:12.688 BRT][INFO ][net.sourceforge.jnlp.Parser] good - your JRE - 1.8.0_372 - match requested JRE - 1.3+
[ITW-CORE][2023-06-20 15:59:12.691 BRT][INFO ][net.adoptopenjdk.icedteaweb.xmlparser.MalformedXMLParser] Using MalformedXMLParser
[ITW-CORE][2023-06-20 15:59:12.697 BRT][INFO ][net.sourceforge.jnlp.Parser] Homepage: null
[ITW-CORE][2023-06-20 15:59:12.697 BRT][INFO ][net.sourceforge.jnlp.Parser] Description: Host On-Demand
[ITW-CORE][2023-06-20 15:59:12.697 BRT][INFO ][net.sourceforge.jnlp.JNLPFile] Acceptable vendor tag found, contains: IBM Corporation
[ITW-CORE][2023-06-20 15:59:12.697 BRT][INFO ][net.sourceforge.jnlp.Parser] good - your JRE - 1.8.0_372 - match requested JRE - 1.3+
[ITW-CORE][2023-06-20 15:59:12.715 BRT][INFO ][net.adoptopenjdk.icedteaweb.resources.cache.CacheImpl] isCached: CacheKey{location=https://hod.serpro.gov.br/hod/images/hodSplash.png, version=null} = true
[ITW-CORE][2023-06-20 15:59:13.113 BRT][INFO ][net.adoptopenjdk.icedteaweb.resources.cache.CacheImpl] isUpToDate: CacheKey{location=https://hod.serpro.gov.br/hod/images/hodSplash.png, version=null} = true
[ITW-CORE][2023-06-20 15:59:13.141 BRT][INFO ][net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader] New classloader: file:/Users/kafran/Downloads/hodcivws.jnlp
[ITW-CORE][2023-06-20 15:59:13.144 BRT][INFO ][net.adoptopenjdk.icedteaweb.resources.cache.CacheImpl] isCached: CacheKey{location=https://hod.serpro.gov.br/hod/WSCachedSupporter2.jar, version=null} = true
[ITW-CORE][2023-06-20 15:59:13.144 BRT][INFO ][net.adoptopenjdk.icedteaweb.resources.cache.CacheImpl] isCached: CacheKey{location=https://hod.serpro.gov.br/hod/CachedAppletInstaller2.jar, version=null} = true
[ITW-CORE][2023-06-20 15:59:13.215 BRT][INFO ][net.adoptopenjdk.icedteaweb.resources.cache.CacheImpl] isUpToDate: CacheKey{location=https://hod.serpro.gov.br/hod/WSCachedSupporter2.jar, version=null} = true
[ITW-CORE][2023-06-20 15:59:13.359 BRT][INFO ][net.adoptopenjdk.icedteaweb.resources.cache.CacheImpl] isUpToDate: CacheKey{location=https://hod.serpro.gov.br/hod/CachedAppletInstaller2.jar, version=null} = true
[ITW-APP ][2023-06-20 15:59:13.597 BRT][ERROR][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] Warning: the fonts "Times" and "Lucida Bright" are not available for the Java logical font "Serif", which may have unexpected appearance or behavior. Re-enable the "Times" font to remove this warning.
[ITW-CORE][2023-06-20 15:59:13.648 BRT][INFO ][net.adoptopenjdk.icedteaweb.manifest.ManifestAttributesChecker] Codebase matches codebase manifest attribute, and application is signed. Continuing. See: http://docs.oracle.com/javase/7/docs/technotes/guides/jweb/security/no_redeploy.html for details.
[ITW-CORE][2023-06-20 15:59:13.653 BRT][INFO ][net.sourceforge.jnlp.cache.NativeLibraryStorage] Activate native: https://hod.serpro.gov.br/hod/WSCachedSupporter2.jar
[ITW-CORE][2023-06-20 15:59:13.653 BRT][INFO ][net.sourceforge.jnlp.cache.NativeLibraryStorage] Activate native: https://hod.serpro.gov.br/hod/CachedAppletInstaller2.jar
[ITW-CORE][2023-06-20 15:59:13.654 BRT][INFO ][net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader] Added permissions for 2 jars
[ITW-CORE][2023-06-20 15:59:13.655 BRT][INFO ][net.sourceforge.jnlp.runtime.ApplicationInstance] about to set system properties
[ITW-CORE][2023-06-20 15:59:13.657 BRT][INFO ][net.sourceforge.jnlp.Launcher] Starting application [com.ibm.eNetwork.HOD.cached.wssupport.WSCachedSupporter] ...
[ITW-CORE][2023-06-20 15:59:13.674 BRT][INFO ][net.sourceforge.jnlp.Launcher] Invoking main() with args: []
[ITW-APP ][2023-06-20 15:59:13.995 BRT][ERROR][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] javax.jnlp.UnavailableServiceException: javax.jnlp.IntegrationService
[ITW-APP ][2023-06-20 15:59:13.996 BRT][ERROR][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] 	at net.sourceforge.jnlp.services.XServiceManagerStub.lookup(XServiceManagerStub.java:107)
[ITW-APP ][2023-06-20 15:59:13.996 BRT][ERROR][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] 	at javax.jnlp.ServiceManager.lookup(ServiceManager.java:25)
[ITW-APP ][2023-06-20 15:59:13.996 BRT][ERROR][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] 	at com.ibm.eNetwork.HOD.cached.wssupport.WSCachedSupporter.recreateShortcut(Unknown Source)
[ITW-APP ][2023-06-20 15:59:13.996 BRT][ERROR][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] 	at com.ibm.eNetwork.HOD.cached.wssupport.WSCachedSupporter.init(Unknown Source)
[ITW-APP ][2023-06-20 15:59:13.997 BRT][ERROR][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] 	at com.ibm.eNetwork.HOD.cached.wssupport.WSCachedSupporter.main(Unknown Source)
[ITW-APP ][2023-06-20 15:59:13.997 BRT][ERROR][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ITW-APP ][2023-06-20 15:59:13.997 BRT][ERROR][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ITW-APP ][2023-06-20 15:59:13.997 BRT][ERROR][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ITW-APP ][2023-06-20 15:59:13.997 BRT][ERROR][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] 	at java.lang.reflect.Method.invoke(Method.java:498)
[ITW-APP ][2023-06-20 15:59:13.998 BRT][ERROR][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] 	at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:406)
[ITW-APP ][2023-06-20 15:59:13.998 BRT][ERROR][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] 	at net.sourceforge.jnlp.Launcher.access$300(Launcher.java:71)
[ITW-APP ][2023-06-20 15:59:13.998 BRT][ERROR][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] 	at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:660)
[ITW-CORE][2023-06-20 15:59:14.013 BRT][INFO ][net.sourceforge.jnlp.util.logging.OutputController] Increase polling interval for shutdown phase
[ITW-CORE][2023-06-20 15:59:14.014 BRT][INFO ][net.adoptopenjdk.icedteaweb.resources.cache.CacheImpl] Other instances of javaws are running
[ITW-CORE][2023-06-20 15:59:14.015 BRT][INFO ][net.adoptopenjdk.icedteaweb.resources.cache.CacheImpl] Cannot clear the cache at this time. Try later. If the problem persists, try closing your browser(s) & JNLP applications. At the end you can try to kill all java applications. You can clear cache by javaws -Xclearcache or via itw-settings Cache -> View files -> Purge
```

**Comment by kafran** [comment]
Just for future reference, I could run it with Zulu 8.0.372 and Azul IcedTea-Web 1.8.8 portable on MacOS Apple Silicon.
