### ISSUE TITLE
More user-friendly error handling with download problems (yet again NPE in JNLPFileFactory)

### ISSUE THREAD

**Issue by in-fke** [karakun/OpenWebStart#545]
We are still getting customers complaining about error dialogs where it's not clear, what the problem is.
It's still the exception stack like in https://github.com/karakun/OpenWebStart/issues/226
I figure there are some things that were solved, https://github.com/AdoptOpenJDK/IcedTea-Web/pull/846, but just today, I erratically (once, could not reproduce) got the following stack.

```
net.sourceforge.jnlp.LaunchException: Fatal: Read Error: Could not read or parse the JNLP file at 'https://SITE/PATH-TO.jnlp'. You can try to download this file manually and send it as bug report to IcedTea-Web team.
    at net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:332)
    at net.sourceforge.jnlp.Launcher.launch(Launcher.java:192)
    at net.sourceforge.jnlp.runtime.Boot.launch(Boot.java:355)
    at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:335)
    at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:73)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at net.sourceforge.jnlp.runtime.Boot.runMain(Boot.java:279)
    at net.sourceforge.jnlp.runtime.Boot.mainWithReturnCode(Boot.java:132)
    at net.sourceforge.jnlp.runtime.Boot.main(Boot.java:114)
Caused by: java.io.IOException: java.lang.NullPointerException: name can't be null
    at net.sourceforge.jnlp.JNLPFileFactory.openURL(JNLPFileFactory.java:107)
    at net.sourceforge.jnlp.JNLPFileFactory.create(JNLPFileFactory.java:79)
    at net.sourceforge.jnlp.JNLPFileFactory.create(JNLPFileFactory.java:63)
    at net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:300)
    ... 8 more
Caused by: java.lang.NullPointerException: name can't be null
    at java.base/java.io.FilePermission.init(FilePermission.java:321)
    at java.base/java.io.FilePermission.<init>(FilePermission.java:488)
    at java.base/java.lang.SecurityManager.checkRead(SecurityManager.java:661)
    at java.base/java.io.FileInputStream.<init>(FileInputStream.java:146)
    at net.sourceforge.jnlp.JNLPFileFactory.openURL(JNLPFileFactory.java:103)
    ... 11 more
```

**I would request to add some more null checks and to throw more specific exceptions that can be caught on the UI Level so to show the user that there was a "download problem".**

**Comment by in-fke** [comment]
This even happens (same stack, I guess) if the server responds with a 404.
The user is presented the NPE, while it's a plain 404.

```
[ITW-CORE][2024-03-19 14:46:04.282 MEZ][DEBUG][net.adoptopenjdk.icedteaweb.resources.initializer.UrlProber] URL connection 'http://localhost/path-to.jnlp' header fields: {null=[HTTP/1.1 404], Server=[nginx/1.21.3], Connection=[keep-alive], Content-Language=[en], Date=[Tue, 19 Mar 2024 13:46:04 GMT], Content-Type=[text/html;charset=utf-8]}
[ITW-CORE][2024-03-19 14:46:04.282 MEZ][DEBUG][net.adoptopenjdk.icedteaweb.resources.initializer.BaseResourceInitializer] For [l=http://localhost/path-to.jnlp v=null s=I] the server returned 404 code for HEAD request for http://localhost/path-to.jnlp
[ITW-CORE][2024-03-19 14:46:04.282 MEZ][DEBUG][net.adoptopenjdk.icedteaweb.resources.initializer.BaseResourceInitializer] failed to determine best URL: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Server returned 404 for http://localhost/path-to.jnlp
[ITW-CORE][2024-03-19 14:46:04.283 MEZ][DEBUG][net.adoptopenjdk.icedteaweb.resources.initializer.UnversionedResourceInitializer] Failed to determine best URL for [l=http://localhost/path-to.jnlp v=null s=I] will try all of [http://localhost/path-to.jnlp]
[ITW-CORE][2024-03-19 14:46:04.287 MEZ][DEBUG][net.adoptopenjdk.icedteaweb.resources.downloader.BaseResourceDownloader] Will download in background: http://localhost/path-to.jnlp
[ITW-CORE][2024-03-19 14:46:04.288 MEZ][DEBUG][com.openwebstart.proxy.direct.DirectProxyProvider] Using NO_PROXY for http://localhost/path-to.jnlp
[ITW-CORE][2024-03-19 14:46:04.293 MEZ][DEBUG][net.adoptopenjdk.icedteaweb.resources.downloader.BaseResourceDownloader] Exception while downloading resource [l=http://localhost/path-to.jnlp v=null s=I] from http://localhost/path-to.jnlp - message: http://localhost/path-to.jnlp cause: java.io.FileNotFoundException: http://localhost/path-to.jnlp 
[ITW-CORE][2024-03-19 14:46:04.293 MEZ][DEBUG][net.adoptopenjdk.icedteaweb.resources.downloader.BaseResourceDownloader] downloadFrom exception: http://localhost/path-to.jnlp
[ITW-CORE][2024-03-19 14:46:04.295 MEZ][ERROR][net.adoptopenjdk.icedteaweb.resources.downloader.BaseResourceDownloader] Could not download resource [l=http://localhost/path-to.jnlp v=null s=I] from any of theses urls [http://localhost/path-to.jnlp] caused byExecutionException: java.io.FileNotFoundException: http://localhost/path-to.jnlp caused by FileNotFoundException: http://localhost/path-to.jnlp caused by FileNotFoundException: http://localhost/path-to.jnlp
[ITW-CORE][2024-03-19 14:46:04.295 MEZ][DEBUG][net.adoptopenjdk.icedteaweb.resources.ResourceTracker] Download done. Shutting down executor
[ITW-CORE][2024-03-19 14:46:04.296 MEZ][DEBUG][net.adoptopenjdk.icedteaweb.resources.ResourceTracker] Error flag set for resource 'http://localhost/path-to.jnlp'. Can not return a local file for the resource
[ITW-CORE][2024-03-19 14:46:04.296 MEZ][DEBUG][net.adoptopenjdk.icedteaweb.client.GuiLaunchHandler] HandleLaunchError Sbow BasicExceptionDialog Fatal: Read Error: Could not read or parse the JNLP file at 'http://localhost/path-to.jnlp'. You can try to download this file manually and send it as bug report to IcedTea-Web team.
[ITW-CORE][2024-03-19 14:46:04.297 MEZ][ERROR][net.sourceforge.jnlp.AbstractLaunchHandler]
netx: Read Error: Could not read or parse the JNLP file at 'http://localhost/path-to.jnlp'. (java.lang.NullPointerException ())
net.sourceforge.jnlp.LaunchException: Fatal: Read Error: Could not read or parse the JNLP file at 'http://localhost/path-to.jnlp'. You can try to download this file manually and send it as bug report to IcedTea-Web team.
	at net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:333)
	at net.sourceforge.jnlp.Launcher.launch(Launcher.java:193)
	at net.sourceforge.jnlp.runtime.Boot.launch(Boot.java:355)
	at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:335)
	at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:73)
	at java.security.AccessController.doPrivileged(Native Method)
	at net.sourceforge.jnlp.runtime.Boot.runMain(Boot.java:279)
	at net.sourceforge.jnlp.runtime.Boot.mainWithReturnCode(Boot.java:132)
	at net.sourceforge.jnlp.runtime.Boot.main(Boot.java:114)
	at com.openwebstart.launcher.PhaseTwoWebStartLauncher.main(PhaseTwoWebStartLauncher.java:93)
	at com.openwebstart.launcher.OpenWebStartLauncher.main(OpenWebStartLauncher.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)
	at com.install4j.runtime.launcher.WinLauncher.main(WinLauncher.java:25)
Caused by: java.io.IOException: java.lang.NullPointerException
	at net.sourceforge.jnlp.JNLPFileFactory.openURL(JNLPFileFactory.java:107)
	at net.sourceforge.jnlp.JNLPFileFactory.create(JNLPFileFactory.java:79)
	at net.sourceforge.jnlp.JNLPFileFactory.create(JNLPFileFactory.java:63)
	at net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:301)
	... 17 more
Caused by: java.lang.NullPointerException
	at java.io.FileInputStream.<init>(FileInputStream.java:130)
	at net.sourceforge.jnlp.JNLPFileFactory.openURL(JNLPFileFactory.java:103)
	... 20 more
[ITW-CORE][2024-03-19 14:46:04.297 MEZ][ERROR][net.sourceforge.jnlp.runtime.Boot]
failed to launch
net.sourceforge.jnlp.LaunchException: Fatal: Read Error: Could not read or parse the JNLP file at 'http://localhost/path-to.jnlp'. You can try to download this file manually and send it as bug report to IcedTea-Web team.
	at net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:333)
	at net.sourceforge.jnlp.Launcher.launch(Launcher.java:193)
	at net.sourceforge.jnlp.runtime.Boot.launch(Boot.java:355)
	at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:335)
	at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:73)
	at java.security.AccessController.doPrivileged(Native Method)
	at net.sourceforge.jnlp.runtime.Boot.runMain(Boot.java:279)
	at net.sourceforge.jnlp.runtime.Boot.mainWithReturnCode(Boot.java:132)
	at net.sourceforge.jnlp.runtime.Boot.main(Boot.java:114)
	at com.openwebstart.launcher.PhaseTwoWebStartLauncher.main(PhaseTwoWebStartLauncher.java:93)
	at com.openwebstart.launcher.OpenWebStartLauncher.main(OpenWebStartLauncher.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)
	at com.install4j.runtime.launcher.WinLauncher.main(WinLauncher.java:25)
Caused by: java.io.IOException: java.lang.NullPointerException
	at net.sourceforge.jnlp.JNLPFileFactory.openURL(JNLPFileFactory.java:107)
	at net.sourceforge.jnlp.JNLPFileFactory.create(JNLPFileFactory.java:79)
	at net.sourceforge.jnlp.JNLPFileFactory.create(JNLPFileFactory.java:63)
	at net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:301)
	... 17 more
Caused by: java.lang.NullPointerException
	at java.io.FileInputStream.<init>(FileInputStream.java:130)
	at net.sourceforge.jnlp.JNLPFileFactory.openURL(JNLPFileFactory.java:103)
	... 20 more
[ITW-CORE][2024-03-19 14:46:04.297 MEZ][DEBUG][net.sourceforge.jnlp.runtime.Boot] Exiting Boot.mainWithReturnCode() with 1
[ITW-CORE][2024-03-19 14:46:04.297 MEZ][DEBUG][net.sourceforge.jnlp.runtime.JNLPRuntime] Waiting for exception dialog to be closed
```
