### ISSUE TITLE
JNLP wont work with plus sign + in file name

### ISSUE THREAD

**Issue by Tartarga** [karakun/OpenWebStart#599]
Not my application but I'm testing our vendor's JNLP. It downloads other JNLPS but openwebstart log gives a file not found when there is a + sign in the file name

**Comment by Tartarga** [comment]
Example, note + is a space on the 2nd part of the error
`net.sourceforge.jnlp.LaunchException: Fatal: Read Error: Could not read or parse the JNLP file at 'file:/C:/Users/X/Downloads/launch+2.jnlp'. You can try to download this file manually and send it as bug report to IcedTea-Web team.
	at net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:333)
	at net.sourceforge.jnlp.Launcher.launch(Launcher.java:193)
	at net.sourceforge.jnlp.runtime.Boot.launch(Boot.java:355)
	at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:335)
	at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:73)
	at java.security.AccessController.doPrivileged(Native Method)
	at net.sourceforge.jnlp.runtime.Boot.runMain(Boot.java:279)
	at net.sourceforge.jnlp.runtime.Boot.mainWithReturnCode(Boot.java:132)
	at net.sourceforge.jnlp.runtime.Boot.main(Boot.java:114)
	at com.openwebstart.launcher.PhaseTwoWebStartLauncher.main(PhaseTwoWebStartLauncher.java:93)
	at com.openwebstart.launcher.OpenWebStartLauncher.main(OpenWebStartLauncher.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)
	at com.install4j.runtime.launcher.WinLauncher.main(WinLauncher.java:25)
Caused by: java.io.FileNotFoundException: C:\Users\X\Downloads\launch 2.jnlp (The system cannot find the file specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
`

**Comment by jajajaneeneenee** [comment]
I had exactly the same problem today – I wanted to rename a JNLP of JOSM (OpenStreetMap editor – see [https://josm.openstreetmap.de/](https://josm.openstreetmap.de/)) from “`josm-latest.jnlp`” to “`JOSM latest Webstart (pre-release, not fully tested, with JAVA 11+).jnlp`” and got an error message when trying to use it:

`net.sourceforge.jnlp.LaunchException: Fatal: Read Error: Could not read or parse the JNLP file at 'file:/Users/xxx/Downloads/JOSM%20latest%20Webstart%20(pre-release,%20not%20fully%20tested,%20with%20JAVA%2011+).jnlp'. You can try to download this file manually and send it as bug report to IcedTea-Web team.`

When I remove the “`+`” character from the file name, it works ... It would be nice (or actually necessary) if you could use all the characters allowed by the system in file names!

My system:
* macOS 10.14.6 (I know, it's old ... but it's good for me ...)
* OpenWebStart v1.10.1 with JAVA JDK Azul 17.0.4 (JOSM is working fine with this version, I had problems with JAVA 21.x.x)
