### ISSUE TITLE
java.lang.NullPointerException: name can't be null

### ISSUE THREAD

**Issue by andreatera** [karakun/OpenWebStart#601]
Hi,

we do get following error since version 1.10.0 (Windows only):
```
net.sourceforge.jnlp.LaunchException: Fatal: Read Error: Could not read or parse the JNLP file at 'file:/C:/Users/XXXX/Downloads/client.jnlp'. You can try to download this file manually and send it as bug report to IcedTea-Web team.
	at net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:333)
	at net.sourceforge.jnlp.Launcher.launch(Launcher.java:193)
	at net.sourceforge.jnlp.runtime.Boot.launch(Boot.java:355)
	at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:335)
	at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:73)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at net.sourceforge.jnlp.runtime.Boot.runMain(Boot.java:279)
	at net.sourceforge.jnlp.runtime.Boot.mainWithReturnCode(Boot.java:132)
	at net.sourceforge.jnlp.runtime.Boot.main(Boot.java:114)
Caused by: java.io.IOException: java.lang.NullPointerException: name can't be null
	at net.sourceforge.jnlp.JNLPFileFactory.openURL(JNLPFileFactory.java:132)
	at net.sourceforge.jnlp.JNLPFileFactory.create(JNLPFileFactory.java:104)
	at net.sourceforge.jnlp.JNLPFileFactory.create(JNLPFileFactory.java:88)
	at net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:324)
	... 8 more
Caused by: java.lang.NullPointerException: name can't be null
	at java.base/java.io.FilePermission.init(FilePermission.java:321)
	at java.base/java.io.FilePermission.<init>(FilePermission.java:488)
	at java.base/java.lang.SecurityManager.checkRead(SecurityManager.java:661)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:146)
	at net.sourceforge.jnlp.JNLPFileFactory.openURL(JNLPFileFactory.java:128)
	... 11 more
```

Some notes:
- we do use bellsoft-jdk11
- with the same JNLP file until OWS version 1.9.1 it worked well.
- on Linux Ubuntu with the same OWS version the issue doesn't appear.

Following the masked client.jnlp for reference.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<jnlp spec="1.0+" codebase="https://xxxxxx:443/scsl/WebStart" href="client.jnlp&#063;language=english">
        <information>
                <title>Tango Client</title>
                <vendor>XXXXX</vendor>
                <icon href="Tango64x64.png"/>
        </information>
        <security>
                <all-permissions/>
        </security>
        <resources>
                <!-- Application Resources -->
                <j2se version="1.8+" java-vm-args="-Xmx1g" vendor="BellSoft"/>
                <property name="apple.laf.useScreenMenuBar" value="true"/>
                <property name="file.encoding" value="UTF-8"/>
                <jar href="lib/jtt-8.104.jar"/>
                <jar href="lib/weld-ejb-3.1.9.Final.jar"/>
                <jar href="lib/controlsfx-8.40.11.jar"/>
                <jar href="lib/weld-environment-common-3.1.9.Final.jar"/>
                <jar href="lib/tow-ws-stubs-14.0.jar"/>
                <jar href="lib/weld-se-shaded-3.1.9.Final.jar"/>
                <jar href="lib/org-netbeans-api-annotations-common-RELEASE81.jar"/>
                <jar href="lib/jakarta.mail-1.6.7.payara-p1.jar"/>
                <jar href="lib/org-openide-util-ui-RELEASE81.jar"/>
                <jar href="lib/jakarta.enterprise.cdi-api-2.0.2.jar"/>
                <jar href="lib/shared-4.94.jar"/>
                <jar href="lib/weld-jta-3.1.9.Final.jar"/>
                <jar href="lib/slf4j-jdk14-1.7.25.jar"/>
                <jar href="lib/service.core-14.0.jar"/>
                <jar href="lib/commons-logging-1.2.jar"/>
                <jar href="lib/jsoup-1.14.2.jar"/>
                <jar href="lib/jboss-el-api_3.0_spec-2.0.0.Final.jar"/>
                <jar href="lib/jboss-interceptors-api_1.2_spec-2.0.0.Final.jar"/>
                <jar href="lib/jboss-annotations-api_1.3_spec-2.0.1.Final.jar"/>
                <jar href="lib/commons-collections-3.2.2.jar"/>
                <jar href="lib/jsr305-3.0.1.jar"/>
                <jar href="lib/weld-probe-core-3.1.9.Final.jar"/>
                <jar href="lib/weld-core-impl-3.1.9.Final.jar"/>
                <jar href="lib/elayout-2.0.jar"/>
                <jar href="lib/org-openide-util-RELEASE81.jar"/>
                <jar href="lib/org-openide-util-lookup-RELEASE81.jar"/>
                <jar href="lib/slf4j-api-1.7.25.jar"/>
                <jar href="lib/jboss-logging-3.4.3.Final.jar"/>
                <jar href="lib/weld-osgi-bundle-3.1.9.Final.jar"/>
                <jar href="lib/gui.core-14.0.jar"/>
                <jar href="lib/estarter-1.0.jar"/>
                <jar href="lib/guava-20.0.jar"/>
                <jar href="lib/commons-beanutils-1.9.4.jar"/>
                <jar href="lib/jboss-transaction-api_1.3_spec-2.0.0.Final.jar"/>
                <jar href="lib/commons-lang3-3.12.0.jar"/>
                <jar href="lib/jakarta.activation-1.2.1.jar"/>
                <jar href="lib/libphonenumber-5.9.jar"/>
                <jar href="lib/alloy-1.0.jar"/>
                <jar href="lib/jboss-classfilewriter-1.2.5.Final.jar"/>
                <jar href="lib/cloning-1.7.4.jar"/>
                <jar href="lib/jboss-ejb-api_3.2_spec-2.0.0.Final.jar"/>
                <jar href="lib/webservices-14.0.jar"/>
                <jar href="lib/gson-2.4.jar"/>
                <jar href="lib/weld-spi-3.1.SP4.jar"/>
                <jar href="lib/jxl-2.5.7.jar"/>
                <jar href="lib/common.core-14.0.jar"/>
                <jar href="lib/commons-validator-1.7.jar"/>
                <jar href="lib/eaf-api-jse6-2.11.8.jar"/>
                <jar href="lib/data.core-14.0.jar"/>
                <jar href="lib/org-netbeans-api-visual-RELEASE81.jar"/>
                <jar href="lib/weld-web-3.1.9.Final.jar"/>
                <jar href="lib/weld-api-3.1.SP4.jar"/>
                <jar href="lib/fast-and-simple-minify-1.0.jar"/>
                <jar href="lib/weld-se-core-3.1.9.Final.jar"/>
                <jar href="lib/weld-jsf-3.1.9.Final.jar"/>
                <jar href="lib/exceltool-1.0.3.jar"/>
                <jar href="lib/jakarta.inject-api-1.0.jar"/>
                <jar href="lib/jfxtras-common-8.0-r4.jar"/>
                <jar href="lib/jfxtras-controls-8.0-r4.jar"/>
                <jar href="lib/joda-time-2.10.14.jar"/>
                <jar href="lib/joor-0.9.5.jar"/>
        </resources>
        <application-desc
                        name="Tango Client"
                        main-class="xxxxxxxx">
                <argument>--configuration=xxxx</argument>
                <argument>--trace=3</argument>
                <argument>--configuration-login</argument>
                <argument>--server=https://xxxxxxxxx:443/scsl/</argument>
                <argument>--logfile=$TEMP/xxxxxxx.log</argument>
                <argument>--no-update</argument>
                <argument>--no-update</argument>
                <argument>--no-update</argument>
                <argument>--no-update</argument>
        </application-desc>
</jnlp>
```

Thanks in advance for any support.

**Comment by FelixJongleur42** [comment]
Along the lines of #545, #450, #226
Happened to me when proxy settings where initially wrong and then corrected.

**Comment by sclassen** [comment]
yes this NPE usually indicates a problem while downloading the JNLP or another resource.
Check you log files for any errors during download
