### ISSUE TITLE
External Launch Error: Could not determine location of javaws.jar on Linux Mint

### ISSUE THREAD

**Issue by NCothran** [karakun/OpenWebStart#609]
After a recent Linux update, whenever I try to run a .JNLP file with Openwebstart I am getting this error:

net.sourceforge.jnlp.LaunchException: Fatal: External Launch Error: Could not determine location of javaws.jar. An attempt was made to launch a JNLP file in another JVM, but the javaws.jar could not be located.  In order to launch in an external JVM, the runtime must be able to locate the javaws.jar file.
	at net.sourceforge.jnlp.Launcher.launchExternal(Launcher.java:289)
	at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:368)
	at net.sourceforge.jnlp.Launcher.access$300(Launcher.java:72)
	at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:661)
Caused by: java.lang.NullPointerException
	at com.openwebstart.jvm.LocalRuntimeManager.loadRuntimes(LocalRuntimeManager.java:148)
	at com.openwebstart.jvm.JavaRuntimeManager.getJavaRuntimeProvider(JavaRuntimeManager.java:29)
	at com.openwebstart.extensionpoint.OwsExtensionPoint.createJvmLauncher(OwsExtensionPoint.java:36)
	at net.sourceforge.jnlp.Launcher.launchExternal(Launcher.java:286)

On top of that, when I try to open Openwebstart settings it hangs on the initial banner and never opens, so I can't change any of the settings.

Any ideas?

**Comment by NCothran** [comment]
On further examination, this appears to be a permissions issue. If I run the JNLP files as sudo from the terminal it opens, but simply clicking them and running them gives the error. How can I fix that?

**Comment by NCothran** [comment]
Finally solved it myself. If anyone else encounters this issue, just right click on any .jnlp file, open properties > Open With, then make a custom executable and put 'sudo javaws' as the default application. Now my OpenWebStart java apps run without the need to open the folder as root.
