### ISSUE TITLE
Could not initialize applet

### ISSUE THREAD

**Issue by carljmosca** [karakun/OpenWebStart#61]
The first time I tried OpenWebStart on a Mac with this applet, it loaded nicely but it no longer works.

I am guessing I have changed something in the configuration but so far I cannot figure out what that might be.

Any suggestions on what I might try?

net.sourceforge.jnlp.LaunchException: Fatal: Initialization Error: Could not initialize applet. For more information click "more information button".
	at net.sourceforge.jnlp.Launcher.createApplet(Launcher.java:650)
	at net.sourceforge.jnlp.Launcher.launchApplet(Launcher.java:532)
	at net.sourceforge.jnlp.Launcher.access$400(Launcher.java:70)
	at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:760)
Caused by: java.lang.NullPointerException
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.getAccessControlContextForClassLoading(JNLPClassLoader.java:2080)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.findClass(JNLPClassLoader.java:1584)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader$CodeBaseClassLoader.findClass(JNLPClassLoader.java:2352)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.initializeResources(JNLPClassLoader.java:754)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.<init>(JNLPClassLoader.java:346)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.createInstance(JNLPClassLoader.java:419)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.getInstance(JNLPClassLoader.java:491)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.getInstance(JNLPClassLoader.java:464)
	at net.sourceforge.jnlp.Launcher.createApplet(Launcher.java:608)

**Comment by hendrikebbers** [comment]
>  with this applet

Can you give us more information about the application you wanted to start?

**Comment by carljmosca** [comment]
I know it currently works with Java Web Start with no issues and it started OK with OpenWebStart at least once.

I did not write this one and have only briefly looked at the sources.

I am wondering if this is a cache/settings issue unique to OpenWebStart or if it's related to the app.  Guessing the later based on your question.

I don't know what else to provide at this point.  I will keep digging.

**Comment by sclassen** [comment]
@carljmosca can you try the following snapshot version to see if it fixes your problem

https://cloud.karakun.com/index.php/s/7P43naEYDeDQxgd

**Comment by sclassen** [comment]
We decided to not support applets
