### ISSUE TITLE
prevent stacktraces from JNLPClassLoader

### ISSUE THREAD

**Issue by Horcrux7** [karakun/OpenWebStart#62]
Is there any option to prevent the logging of the JNLPClassLoader. I receive thousand stacktrace like the follow from all the resources that are resolved from my classloader without problems. The JNLPClassLoader is the parent classloader which will ask first.
```
Mon Oct 28 16:32:32 CET 2019 [ERROR  ] net.sourceforge.jnlp.runtime.JNLPClassLoader: 
ERROR 
java.lang.ClassNotFoundException: com.inet.plugin.ServerPlugin
     at net.sourceforge.jnlp.runtime.JNLPClassLoader.loadClassExt(JNLPClassLoader.java:1636)
     at net.sourceforge.jnlp.runtime.JNLPClassLoader.loadClass(JNLPClassLoader.java:1455)
     at com.inet.shared.loader.AsynURLClassLoader.loadClass(SourceFile:366) 

```

**Comment by hendrikebbers** [comment]
In the new version of OpenWebStart the logging of the Classloader looks fine.
