### ISSUE TITLE
Could not read or parse the JNLP file

### ISSUE THREAD

**Issue by bjorndarri** [karakun/OpenWebStart#68]
I'm running an application in Windows by clicking a link to a jnlp file ('ata_dev.jnlp'), first time around everything works as expected, the file is downloaded (by Chrome) and the application runs, but the second time the jnlp file is downloaded again and gets a new name 'ata_dev (1).jnlp', since the file already exists in the downloads folder. OpenWebStart then fails to run with the new jnlp file.

Here's the error message, the relevant line in bold, looks like the problem lies in URL-encoding:

net.sourceforge.jnlp.LaunchException: Fatal: Read Error: Could not read or parse the JNLP file. You can try to download this file manually and send it as bug report to IcedTea-Web team.
	at net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:369)
	at net.sourceforge.jnlp.Launcher.launch(Launcher.java:228)
	at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:296)
	at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:78)
	at java.security.AccessController.doPrivileged(Native Method)
	at net.sourceforge.jnlp.runtime.Boot.main(Boot.java:233)
	at com.openwebstart.launcher.PhaseTwoWebStartLauncher.main(PhaseTwoWebStartLauncher.java:81)
	at com.openwebstart.launcher.OpenWebStartLauncher.main(OpenWebStartLauncher.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:85)
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)
	at com.install4j.runtime.launcher.WinLauncher.main(WinLauncher.java:25)
Caused by: java.io.IOException: java.io.FileNotFoundException: **C:\Users\darri\Downloads\ata_dev%20(1).jnlp (The system cannot find the file specified)**
	at net.sourceforge.jnlp.JNLPFile.openURL(JNLPFile.java:386)
	at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:289)
	at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:272)
	at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:257)
	at net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:333)
	... 14 more
Caused by: java.io.FileNotFoundException: C:\Users\darri\Downloads\ata_dev%20(1).jnlp (The system cannot find the file specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at net.sourceforge.jnlp.JNLPFile.openURL(JNLPFile.java:383)
	... 18 more

**Comment by bjorndarri** [comment]
Forgot to add that this problem was introduced in version 0.5.

**Comment by hendrikebbers** [comment]
Just to clarify:

* When you download `ata_dev.jnlp` you can simply start it and everything is working fine.
* When you download the file a second time it will automatically renamed (by the os) to `ata_dev (1).jnlp`
* When you want to start `ata_dev (1).jnlp` OpenWebStart will end with an error 

Is this correct?

**Comment by sclassen** [comment]
could be a problem with the white space in `ata_dev (1).jnlp`

**Comment by hendrikebbers** [comment]
Same error on my machine:

```
Proceeding with jnlp
JNLP file location: /Users/hendrikebbers/Desktop/webstart-monitor (1).jnlp
netx: Read Error: Could not read or parse the JNLP file. (java.io.FileNotFoundException: /Users/hendrikebbers/Desktop/webstart-monitor%20(1).jnlp (No such file or directory) (/Users/hendrikebbers/Desktop/webstart-monitor%20(1).jnlp (No such file or directory)))
net.sourceforge.jnlp.LaunchException: Fatal: Read Error: Could not read or parse the JNLP file. You can try to download this file manually and send it as bug report to IcedTea-Web team.
	at net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:369)
	at net.sourceforge.jnlp.Launcher.launch(Launcher.java:228)
	at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:296)
	at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:78)
	at java.security.AccessController.doPrivileged(Native Method)
	at net.sourceforge.jnlp.runtime.Boot.main(Boot.java:233)
	at com.openwebstart.launcher.PhaseTwoWebStartLauncher.main(PhaseTwoWebStartLauncher.java:81)
Caused by: java.io.IOException: java.io.FileNotFoundException: /Users/hendrikebbers/Desktop/webstart-monitor%20(1).jnlp (No such file or directory)
	at net.sourceforge.jnlp.JNLPFile.openURL(JNLPFile.java:386)
	at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:289)
	at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:272)
	at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:257)
	at net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:333)
	... 6 more
Caused by: java.io.FileNotFoundException: /Users/hendrikebbers/Desktop/webstart-monitor%20(1).jnlp (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at net.sourceforge.jnlp.JNLPFile.openURL(JNLPFile.java:383)
	... 10 more
```
