### ISSUE TITLE
Download failed with "Malformed \uxxxx encoding." only on Windows

### ISSUE THREAD

**Issue by barthel** [karakun/OpenWebStart#70]
OpenWebStart 0.5.1

Stripped JNLP file:
```xml
<?xml version="1.0" encoding="utf-8"?>
<jnlp spec="6.0+" codebase="https://my.domain.test/baseURI">
    <information>
        <title>My Application</title>
    </information>
    <security>
        <all-permissions/>
    </security>
    <update check="timeout" policy="always"/>
    <resources>
        <java version="1.8*"/>
        <jar href="my-library.jar?AUTHSESSION=MY_SESSION_COOKIE_VALUE" download="eager" main="true"/>
    </resources>

    <application-desc main-class="my.Application">
[...]
    </application-desc>
</jnlp>
```

The application resources are located in a protected web domain and requires authentication before download.
That’s the reason why the URL must be enhanced with the session cookie.

My JNLP file works on macOS with OpenWebStart and with the Java WebStart implementation provided by Oracle Java 1.8.
The same JNLP file works on Windows with the Java WebStart implementation provided by Oracle Java 1.8 _*BUT NOT*_ with OpenWebStart.

The stripped log output (Windows):
```
[...]
[sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] NETX Thread# 73f949bb, name My Application: Fri Nov 08 14:15:31 CET 2019 [INFO  ] net.sourceforge.jnlp.cache.NativeLibraryStorage: Activate native: https://my.domain.test/my-library.jar?AUTHSESSION=MY_SESSION_COOKIE_VALUE 
[sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] NETX Thread# 73f949bb, name My Application: Fri Nov 08 14:15:31 CET 2019 [DEBUG  ] net.sourceforge.jnlp.runtime.JNLPClassLoader: Activate jar: https://my.domain.test/my-library.jar?AUTHSESSION=MY_SESSION_COOKIE_VALUE 
[sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] NETX Thread# 73f949bb, name My Application: Fri Nov 08 14:15:31 CET 2019 [INFO  ] net.sourceforge.jnlp.JNLPFile: Acceptable title tag found, contains: My Application 
[sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] NETX Thread# 73f949bb, name My Application: Fri Nov 08 14:15:31 CET 2019 [DEBUG  ] net.adoptopenjdk.icedteaweb.manifest.ManifestAttributesReader: Jars not ready to provide attribute Application-Name 
[sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] NETX Thread# 73f949bb, name My Application: Fri Nov 08 14:15:31 CET 2019 [WARNING] net.sourceforge.jnlp.runtime.JNLPClassLoader: JAR https://my.domain.test/my-library.jar?AUTHSESSION=MY_SESSION_COOKIE_VALUE not found. Continuing. 
[sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] NETX Thread# 73f949bb, name My Application: Fri Nov 08 14:15:31 CET 2019 [WARNING] net.sourceforge.jnlp.runtime.JNLPClassLoader: JAR https://my.domain.test/my-library.jar?AUTHSESSION=MY_SESSION_COOKIE_VALUE not found. Continuing. 
[sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] NETX Thread# 6dc3d3f1, name pool-1-thread-1: Fri Nov 08 14:15:31 CET 2019 [ERROR  ] net.adoptopenjdk.icedteaweb.resources.downloader.BaseResourceDownloader: could not download resource location=https://my.domain.test/my-library.jar?AUTHSESSION=MY_SESSION_COOKIE_VALUE version=null state=INCOMPLETE from any of theses urls [https://my.domain.test/my-library.jar?AUTHSESSION=MY_SESSION_COOKIE_VALUE] 
[sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] NETX Thread# 677e7de1, name itwpool-1-itwthread-2: Fri Nov 08 14:15:31 CET 2019 [DEBUG  ] net.adoptopenjdk.icedteaweb.resources.downloader.BaseResourceDownloader: Exception while downloading resource location=https://my.domain.test/my-library.jar?AUTHSESSION=MY_SESSION_COOKIE_VALUE version=null state=INCOMPLETE from https://my.domain.test/my-library.jar?AUTHSESSION=MY_SESSION_COOKIE_VALUE - Malformed \uxxxx encoding. 
[sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] NETX Thread# 677e7de1, name itwpool-1-itwthread-2: Fri Nov 08 14:15:31 CET 2019 [DEBUG  ] net.adoptopenjdk.icedteaweb.resources.cache.LeastRecentlyUsedCache: Downloading file: https://my.domain.test/my-library.jar?AUTHSESSION=MY_SESSION_COOKIE_VALUE into: C:\Users\myUser\.cache\icedtea-web\cache\0\0\my-library.jar 
[sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] NETX Thread# 677e7de1, name itwpool-1-itwthread-2: Fri Nov 08 14:15:31 CET 2019 [DEBUG  ] net.adoptopenjdk.icedteaweb.resources.downloader.StreamUnpacker: Will use no content-unpacker for 'https://my.domain.test/my-library.jar?AUTHSESSION=MY_SESSION_COOKIE_VALUE' 
[sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] NETX Thread# 677e7de1, name itwpool-1-itwthread-2: Fri Nov 08 14:15:31 CET 2019 [DEBUG  ] net.adoptopenjdk.icedteaweb.resources.downloader.StreamUnpacker: Will use no compression-unpacker for 'https://my.domain.test/my-library.jar?AUTHSESSION=MY_SESSION_COOKIE_VALUE' 
[...]
```

The `my-library.jar` was successfully stored in cache folder and the content of this JAR file is valid.

The application start failed with:

```
net.sourceforge.jnlp.LaunchException: Fatal: Initialization Error: Could not initialize application. The application has not been initialized, for more information execute javaws from the command line.
	at net.sourceforge.jnlp.Launcher.createApplication(Launcher.java:669)
	at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:411)
	at net.sourceforge.jnlp.Launcher.access$300(Launcher.java:69)
	at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:756)
Caused by: net.sourceforge.jnlp.LaunchException: Fatal: Initialization Error: Unknown Main-Class. Could not determine the main class for this application.
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.initializeResources(JNLPClassLoader.java:760)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.<init>(JNLPClassLoader.java:347)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.createInstance(JNLPClassLoader.java:420)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.getInstance(JNLPClassLoader.java:492)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.getInstance(JNLPClassLoader.java:465)
	at net.sourceforge.jnlp.Launcher.createApplication(Launcher.java:661)
	... 3 more
```

**Comment by hendrikebbers** [comment]
What version of OpenWebStart do you use?

**Comment by sclassen** [comment]
There must be some character in the URL which causes conflicts with the property file.
Can you please post the original URL from you log.

Also would be great to get you `recently_used` file from the ${HOME}/.cached/icedtea-web folder

If you do not want to provide the information in public you can send a mail to openwebstart@karakun.com and we will not share it with anybody.

**Comment by barthel** [comment]
This error is also shown if the value of `MY_SESSION_COOKIE_VALUE` is URL encoded with charset `US-ASCII`.

**Comment by barthel** [comment]
The `MY_SESSION_COOKIE` contains a value like this example:
```
9VJUI2u9vF9iTGInp2pXyeXxdQzRF/m/jax0UnzsMTQV1bGQKX/yQx3l12GVxT/xIN2Gn2Mkdo9M0JSuS0m2O+M7oj6kwXOteoYlFl1yXHLea2YPslMWnJCx3jEqngli3KKjuvsMSbxCDXVm2oo9KTDakMQR/NihIuzSMUep5HIDH63wBUbpvP0quEfS5xMeko5QmdhGZYSS9MvMCs3JJFW2EPvY3B31H8CFAUZOEP7VKzrG8iZ5/1KZ0pqkGdUur/u9/8NxztLlNMASlC+X2YtHmFYB96fTlE0qWdvpvmbKs2PYfGT+cDksvxMQsQxf8fiG5eHffgdlqqxtcoZB2v3tpOblRJAmXbWoXb/JJ7/gzwG+oy8+o/qVKxElab6jPGtK5VdupNi8Lshg4H7+k4wANE6cLOmiqvuPRxVp0/hw2Ak71VNs8YqhLBpH8k/whffatO4EttWxtYLlJ12b0GxsoYnStAqzUHigm6GKzFnjsAXkZjz6Tu0iw4aZqzwACE5wFcolJTvEvDC9xv9pzfz/TK5+Fx33if4IowsSQJPoS+LXPOYV36CvEfodFO5BcFfUUg3EuDDUg9WpNGSEjiYxhSnSCbmPVVYUtZ2jqNMWizVVy2MxKXLKV4L9DMGUxNy52vqN/o26SDnVteUmwSpIby2a03vuHCOuK4n5HtoKB32HE3LIt8k31bDqtXyAK41vMvdUppvXXNwlNODrvpCupmxelHE+f9+/kKHT1YVZ14uQIhQOI3IiAm9JkoOcHSzQDh8MVT/Pk9IIkBLU2c25EHpfI4jtJvBGctvvYbdDffbCJ4TLLxNuu0eA0u2KFm/ETAE2WSIn9N+lNlpATPlB00ri1J4H6jXI8YpDrm1bhSJrJngmKxXTe3gjPItfwyT8odudiZ6llzym1kqcO6P6oQMLZUKNGDXZGgyuA+wbnjSdnJfUoL/RgiTcEfmZvg7qVPzQA1KJmwiI25mmlY3zbqmJdM1ZgL4hK4GyvZ0VIdIdv+YCSkstVeaV6zO2V9z+EaLmH7cRfFHLcbhDfwvmvaqRFWgecQK92LOGOTayfvttHjFxW3KZ9B0S9mdvoqVBYBsN3+4lC+icItjpy/3RxEXV2WMuoxt0+ijAXVvKhTt2kQJzaF1xrg36OqYunwMHal3zNuLywH88jQemvDLh9X8Pd7FE
```
