### ISSUE TITLE
AccessControlException when trying to access system property

### ISSUE THREAD

**Issue by xbug42** [karakun/OpenWebStart#76]
OpenWebStart 0.5.1 on Linux

Relevant part of the stacktrace : 
```
java.security.AccessControlException: access denied ("java.util.PropertyPermission" "java.io.tmpdir" "read")
	at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
	at java.base/java.security.AccessController.checkPermission(AccessController.java:895)
	at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:322)
	at net.sourceforge.jnlp.runtime.JNLPSecurityManager.checkPermission(JNLPSecurityManager.java:291)
```

The JNLP includes :
```
<security>
		<all-permissions/>
</security>
```

This JNLP is running fine with Java Web Start / Oracle JDK 8

**Comment by hendrikebbers** [comment]
can you send the rest of the stack trace?

**Comment by xbug42** [comment]
`net.sourceforge.jnlp.LaunchException: Fatal: Launch Error: Could not launch JNLP file. The application has not been initialized, for more information execute javaws/browser from the command line and send a bug report.
	at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:458)
	at net.sourceforge.jnlp.Launcher.access$300(Launcher.java:69)
	at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:756)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:452)
	... 2 more
Caused by: java.security.AccessControlException: access denied ("java.util.PropertyPermission" "java.io.tmpdir" "read")
	at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
	at java.base/java.security.AccessController.checkPermission(AccessController.java:895)
	at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:322)
	at net.sourceforge.jnlp.runtime.JNLPSecurityManager.checkPermission(JNLPSecurityManager.java:291)
	at java.base/java.lang.SecurityManager.checkPropertyAccess(SecurityManager.java:1066)
	at java.base/java.lang.System.getProperty(System.java:810)
	at com.gloptv.util.Bootstrap2.parseArgs(Bootstrap2.java:74)
	at com.gloptv.util.Bootstrap2.<init>(Bootstrap2.java:43)
	at com.gloptv.util.Bootstrap2.main(Bootstrap2.java:161)
	... 7 more
`

**Comment by hendrikebbers** [comment]
We are currently working at the 1.0 release. Once this is done we can have a look at this issue. Can you upload the JNLP file to this issue or send it to openwebstart@karakun.com ?

**Comment by xbug42** [comment]
The JNLP file was sent to openwebstart@karakun.com .

**Comment by sclassen** [comment]
The JNLP looks fine.
Cannot really understand why this is happening.
Does the error persist with the newest version of OpenWebStart?

**Comment by xbug42** [comment]
The error persists with v1.1.0

AccessControlException is raised when calling `System.getProperty("java.io.tmpdir")` although the JNLP includes `<security><all-permissions/></security>`

**Comment by sclassen** [comment]
Could you please provide a full log of a run with the exception.
All I can think of is that because of some previous issue OWS drops the permissions...

**Comment by xbug42** [comment]
Same problem with 1.1.1
Full log sent to openwebstart@karakun.com

**Comment by sclassen** [comment]
thx for the log.
unfortuanately I see nothin suspicious in it.

**Comment by xbug42** [comment]
Are you able to reproduce it ? With something like that :
```
public class Test
{
  public static void main()
  {
    System.out.println(System.getProperty("java.io.tmpdir"));
  }
}
```

**Comment by sclassen** [comment]
We are currently busy reworking classloading and permissions in an effort to support lazy loading.
Once we are done we will have a look at the open issues, including this one

**Comment by AndreasEhret** [comment]
please test with 3.0.0-alpha1

**Comment by Jamila891** [comment]
closed due to inactivity

**Comment by jastax** [comment]
@Jamila891 I'm still running into the same issue in 1.2.1.
If I remember correctly it worked in 3.0.0-alpha1 but my guess is we should be using 1.2.1 in production?
