### ISSUE TITLE
Unexpected error dialog after cancel security warning dialog

### ISSUE THREAD

**Issue by barthel** [karakun/OpenWebStart#79]
OpenWebStart 0.5.1

The application starts and a security dialog is shown:
![Screenshot 2019-11-14 at 10 19 30](https://user-images.githubusercontent.com/1170328/68843481-7981d880-06c8-11ea-9c82-208a852a9d91.png)

After cancel this dialog a new unexpected error dialog is shown:
![Screenshot 2019-11-14 at 10 23 37](https://user-images.githubusercontent.com/1170328/68843682-d41b3480-06c8-11ea-885e-ddc59c0dc6cd.png)

```
[...]
[ITW-JAVAWS-CLIENT][MESSAGE_ALL][Thu Nov 14 10:22:38 CET 2019][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] NETX Thread# 2d37e6d8, name My Application Installation: 
[ITW-JAVAWS-CLIENT][MESSAGE_ALL][Thu Nov 14 10:22:38 CET 2019][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] NETX Thread# 2d37e6d8, name My Application Installation: Thu Nov 14 10:22:38 CET 2019 [ERROR  ] net.sourceforge.jnlp.Launcher: ERROR net.sourceforge.jnlp.LaunchException: Fatal: Initialization Error: Could not initialize application. The application has not been initialized, for more information execute javaws from the command line.     at net.sourceforge.jnlp.Launcher.createApplication(Launcher.java:669)     at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:411)     at net.sourceforge.jnlp.Launcher.access$300(Launcher.java:69)     at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:756) Caused by: net.sourceforge.jnlp.LaunchException: Fatal: Launch Error: Cancelled on user request.     at net.sourceforge.jnlp.security.JNLPAppVerifier.checkTrustWithUser(JNLPAppVerifier.java:132)     at net.sourceforge.jnlp.tools.JarCertVerifier.checkTrustWithUser(JarCertVerifier.java:545)     at net.sourceforge.jnlp.runtime.JNLPClassLoader.checkTrustWithUser(JNLPClassLoader.java:1028)     at net.sourceforge.jnlp.runtime.JNLPClassLoader.initializeResources(JNLPClassLoader.java:777)     at net.sourceforge.jnlp.runtime.JNLPClassLoader.<init>(JNLPClassLoader.java:347)     at net.sourceforge.jnlp.runtime.JNLPClassLoader.createInstance(JNLPClassLoader.java:420)     at net.sourceforge.jnlp.runtime.JNLPClassLoader.getInstance(JNLPClassLoader.java:492)     at net.sourceforge.jnlp.runtime.JNLPClassLoader.getInstance(JNLPClassLoader.java:465)     at net.sourceforge.jnlp.Launcher.createApplication(Launcher.java:661)     ... 3 more 
[ITW-JAVAWS-CLIENT][MESSAGE_ALL][Thu Nov 14 10:22:38 CET 2019][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] NETX Thread# 2d37e6d8, name My Application Installation: 
[ITW-JAVAWS-CLIENT][MESSAGE_ALL][Thu Nov 14 10:22:38 CET 2019][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] NETX Thread# 2d37e6d8, name My Application Installation: Thu Nov 14 10:22:38 CET 2019 [ERROR  ] net.sourceforge.jnlp.AbstractLaunchHandler: netx: Initialization Error: Could not initialize application. (Fatal: Launch Error: Cancelled on user request. ) net.sourceforge.jnlp.LaunchException: Fatal: Initialization Error: Could not initialize application. The application has not been initialized, for more information execute javaws from the command line.     at net.sourceforge.jnlp.Launcher.createApplication(Launcher.java:669)     at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:411)     at net.sourceforge.jnlp.Launcher.access$300(Launcher.java:69)     at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:756) Caused by: net.sourceforge.jnlp.LaunchException: Fatal: Launch Error: Cancelled on user request.     at net.sourceforge.jnlp.security.JNLPAppVerifier.checkTrustWithUser(JNLPAppVerifier.java:132)     at net.sourceforge.jnlp.tools.JarCertVerifier.checkTrustWithUser(JarCertVerifier.java:545)     at net.sourceforge.jnlp.runtime.JNLPClassLoader.checkTrustWithUser(JNLPClassLoader.java:1028)     at net.sourceforge.jnlp.runtime.JNLPClassLoader.initializeResources(JNLPClassLoader.java:777)     at net.sourceforge.jnlp.runtime.JNLPClassLoader.<init>(JNLPClassLoader.java:347)     at net.sourceforge.jnlp.runtime.JNLPClassLoader.createInstance(JNLPClassLoader.java:420)     at net.sourceforge.jnlp.runtime.JNLPClassLoader.getInstance(JNLPClassLoader.java:492)     at net.sourceforge.jnlp.runtime.JNLPClassLoader.getInstance(JNLPClassLoader.java:465)     at net.sourceforge.jnlp.Launcher.createApplication(Launcher.java:661)     ... 3 more 
[ITW-JAVAWS-CLIENT][MESSAGE_ALL][Thu Nov 14 10:22:38 CET 2019][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] NETX Thread# 35fb3008, name AWT-EventQueue-0: Thu Nov 14 10:22:38 CET 2019 [DEBUG  ] net.adoptopenjdk.icedteaweb.client.parts.dialogs.security.SecurityDialog: Returning value: NO 
[ITW-JAVAWS-CLIENT][MESSAGE_ALL][Thu Nov 14 10:22:38 CET 2019][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] NETX Thread# 35fb3008, name AWT-EventQueue-0: Thu Nov 14 10:22:38 CET 2019 [DEBUG  ] net.adoptopenjdk.icedteaweb.client.parts.dialogs.security.SecurityDialog: Setting value: NO 
[ITW-JAVAWS-CLIENT][MESSAGE_ALL][Thu Nov 14 10:14:49 CET 2019][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] NETX Thread# 35fb3008, name AWT-EventQueue-0: Thu Nov 14 10:14:49 CET 2019 [DEBUG  ] net.adoptopenjdk.icedteaweb.client.parts.dialogs.security.SecurityDialog: Setting value: null 
[ITW-JAVAWS-CLIENT][MESSAGE_ALL][Thu Nov 14 10:14:49 CET 2019][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] NETX Thread# 35fb3008, name AWT-EventQueue-0: Thu Nov 14 10:14:49 CET 2019 [DEBUG  ] net.sourceforge.jnlp.tools.JarCertVerifier: App has trusted root CA: false 
[ITW-JAVAWS-CLIENT][MESSAGE_ALL][Thu Nov 14 10:14:49 CET 2019][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] NETX Thread# 2d37e6d8, name My Application Installation: Thu Nov 14 10:14:49 CET 2019 [DEBUG  ] net.sourceforge.jnlp.tools.JarCertVerifier: App already has trusted publisher: false 
[ITW-JAVAWS-CLIENT][MESSAGE_ALL][Thu Nov 14 10:14:49 CET 2019][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] NETX Thread# 2d37e6d8, name My Application Installation: Thu Nov 14 10:14:49 CET 2019 [DEBUG  ] net.sourceforge.jnlp.tools.JarCertVerifier: App already has trusted publisher: true 
[ITW-JAVAWS-CLIENT][MESSAGE_ALL][Thu Nov 14 10:14:49 CET 2019][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] NETX Thread# 2d37e6d8, name My Application Installation: Thu Nov 14 10:14:49 CET 2019 [DEBUG  ] net.sourceforge.jnlp.runtime.JNLPClassLoader: Ending check for signed JNLP file... 
[ITW-JAVAWS-CLIENT][MESSAGE_ALL][Thu Nov 14 10:14:49 CET 2019][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] NETX Thread# 2d37e6d8, name My Application Installation: Thu Nov 14 10:14:49 CET 2019 [DEBUG  ] net.sourceforge.jnlp.tools.JarCertVerifier: App already has trusted publisher: true 
[ITW-JAVAWS-CLIENT][MESSAGE_ALL][Thu Nov 14 10:14:49 CET 2019][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] NETX Thread# 2d37e6d8, name My Application Installation: Thu Nov 14 10:14:49 CET 2019 [DEBUG  ] net.sourceforge.jnlp.tools.JarCertVerifier: App already has trusted publisher: true 
[ITW-JAVAWS-CLIENT][MESSAGE_ALL][Thu Nov 14 10:14:49 CET 2019][sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)] NETX Thread# 2d37e6d8, name My Application Installation: Thu Nov 14 10:14:49 CET 2019 [DEBUG  ] net.sourceforge.jnlp.tools.JarCertVerifier: Jar found at /Users/XXXXXXXXXX/.cache/icedtea-web/cache/0/5/my.application.jar has been verified as SIGNED_OK 
[...]
```

**Comment by hendrikebbers** [comment]
can you send the complete log and jnlp file to openwebstart@karakun.com ?

**Comment by hendrikebbers** [comment]
Will be handled after 1.0 release
