### ISSUE TITLE
Error while adding a local Java

### ISSUE THREAD

**Issue by barthel** [karakun/OpenWebStart#87]
OpenWebStart 0.5.1
macOS 10.15.1 Catalina

After a fresh installation of OpenWebStart I start the OpenWebStart Settings.

In JVM Manager I try to find a local Java Installation and end up in error dialog:

![image](https://user-images.githubusercontent.com/1170328/68990274-add4d080-0851-11ea-887a-04d7c76edded.png)

```
java.lang.RuntimeException: Could not find all required properties. Only found {}
	at com.openwebstart.jvm.util.JavaRuntimePropertiesDetector.extractProperties(JavaRuntimePropertiesDetector.java:70)
	at com.openwebstart.jvm.util.JavaRuntimePropertiesDetector.getProperties(JavaRuntimePropertiesDetector.java:58)
	at com.openwebstart.jvm.localfinder.JdkFinder.getLocalJavaRuntime(JdkFinder.java:70)
	at com.openwebstart.func.Result.lambda$of$0(Result.java:75)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:175)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.openwebstart.jvm.localfinder.JdkFinder.findLocalJdks(JdkFinder.java:44)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.openwebstart.jvm.localfinder.JdkFinder.findLocalJdks(JdkFinder.java:33)
	at com.openwebstart.jvm.localfinder.MacRuntimeFinder.findLocalRuntimes(MacRuntimeFinder.java:28)
	at com.openwebstart.jvm.LocalRuntimeManager.lambda$findAndAddLocalRuntimes$10(LocalRuntimeManager.java:264)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at com.openwebstart.jvm.LocalRuntimeManager.findAndAddLocalRuntimes(LocalRuntimeManager.java:261)
	at com.openwebstart.jvm.ui.RuntimeManagerPanel.lambda$null$6(RuntimeManagerPanel.java:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by hendrikebbers** [comment]
looks like OWS finds a 'java' executable on your system that is not real java (or a very old version). The PR https://github.com/karakun/OpenWebStart/pull/89 should add better logging for the error

**Comment by hendrikebbers** [comment]
Will be part of 1.0

**Comment by hendrikebbers** [comment]
Error fixed with https://github.com/karakun/OpenWebStart/pull/95

**Comment by hendrikebbers** [comment]
will be part of 1.1
