### ISSUE TITLE
Could not determine the main class

### ISSUE THREAD

**Issue by HannahBrown** [karakun/OpenWebStart#91]
My application is a Java 11/OpenJFX 11 app. In OpenWebStart  0.4, it ran without error on Windows, Mac and Linux. However, starting with version 0.5.1 and continuing into 1.0, I got this error on Mac and Linux (I have made no changes to the application, and Windows continues to work):

Mon Nov 18 09:48:02 CST 2019 [ERROR  ] net.sourceforge.jnlp.AbstractLaunchHandler:
netx: Initialization Error: Could not initialize application. (Fatal: Initialization Error: Unknown Main-Class. Could not determine the main class for this application.) net.sourceforge.jnlp.LaunchException: Fatal: Initialization Error: Could not initialize application. The application has not been initialized, for more information execute javaws from the command line.
    at net.sourceforge.jnlp.Launcher.createApplication(Launcher.java:669)
    at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:411)
    at net.sourceforge.jnlp.Launcher.access$300(Launcher.java:69)
	at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:756)
Caused by: net.sourceforge.jnlp.LaunchException: Fatal: Initialization Error: Unknown Main-Class. Could not determine the main class for this application.
    at net.sourceforge.jnlp.runtime.JNLPClassLoader.initializeResources(JNLPClassLoader.java:760)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.<init>(JNLPClassLoader.java:347)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.createInstance(JNLPClassLoader.java:420)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.getInstance(JNLPClassLoader.java:492)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.getInstance(JNLPClassLoader.java:465)
	at net.sourceforge.jnlp.Launcher.createApplication(Launcher.java:661)
	... 3 more

net.sourceforge.jnlp.LaunchException: Fatal: Initialization Error: Could not initialize application. The application has not been initialized, for more information execute javaws from the command line.
    at net.sourceforge.jnlp.Launcher.createApplication(Launcher.java:669)
	at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:411)
	at net.sourceforge.jnlp.Launcher.access$300(Launcher.java:69)
	at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:756)
Caused by: net.sourceforge.jnlp.LaunchException: Fatal: Initialization Error: Unknown Main-Class. Could not determine the main class for this application.
    at net.sourceforge.jnlp.runtime.JNLPClassLoader.initializeResources(JNLPClassLoader.java:760)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.<init>(JNLPClassLoader.java:347)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.createInstance(JNLPClassLoader.java:420)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.getInstance(JNLPClassLoader.java:492)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.getInstance(JNLPClassLoader.java:465)
	at net.sourceforge.jnlp.Launcher.createApplication(Launcher.java:661)
	... 3 more

**Comment by hendrikebbers** [comment]
Can you activate debug logging and send us the log file + the JNLP?

**Comment by HannahBrown** [comment]
It turns out that the error could be fixed by clearing the cache. I had previously tried to fix the error by uninstalling and reinstalling OWS, but it appears that the application cache is not cleared when that happens.

Let me know if you still need the debug logs.
